#!/bin/sh

# Script for building all the tests for specific target languages
# Usage: build-tests <lang1> [<lang2> ...]

if [ "$#" -lt 1 ]; then
    echo "Usage: build-tests <lang1> [<lang2> ...]"
    exit 1
fi

# shellcheck disable=SC1091
. "$(dirname "$0")/config"

# shellcheck disable=SC2164
cd ../tests

for lang in "$@"
do
    echo "Building tests for: ${lang}"
    ./spec_kst_to_all -t "${lang}" --all-specs
done

# shellcheck disable=SC2164
cd spec
cp ks/out/* . -r
rm -rf ks/out