#!/bin/sh -ef

# shellcheck disable=SC1091
. "$(dirname "$0")/config"

PYTHONPATH="$PYTHON_RUNTIME_DIR:$FORMATS_COMPILED_DIR/python:spec/python/extra" PYTHONDONTWRITEBYTECODE=1 PYTHONDEVMODE=1 python -m unittest discover -s spec/python/spec
if [ "$ENABLE_WRITE" ] && [ "$ENABLE_WRITE" = "1" ]; then
    PYTHONPATH="$PYTHON_RUNTIME_DIR:$FORMATS_COMPILED_DIR/python:spec/python:spec/python/extra" PYTHONDONTWRITEBYTECODE=1 PYTHONDEVMODE=1 python -m unittest discover -s spec/python/specwrite
fi
