# Autogenerated from KST: please remove this line if doing any edits by hand!

import unittest
from specwrite.common_spec import CommonSpec

from testwrite.union_alignment4_arr_d1_e1_lh import UnionAlignment4ArrD1E1Lh

class TestUnionAlignment4ArrD1E1Lh(CommonSpec.Base):
    def __init__(self, *args, **kwargs):
        super(TestUnionAlignment4ArrD1E1Lh, self).__init__(*args, **kwargs)
        self.struct_class = UnionAlignment4ArrD1E1Lh
        self.src_filename = 'src/UNION_ALIGNMENT4_ARR_D1_E1_LH.bin'
