# Autogenerated from KST: please remove this line if doing any edits by hand!

import unittest
from specwrite.common_spec import CommonSpec

from testwrite.union_alignment8_lh import UnionAlignment8Lh

class TestUnionAlignment8Lh(CommonSpec.Base):
    def __init__(self, *args, **kwargs):
        super(TestUnionAlignment8Lh, self).__init__(*args, **kwargs)
        self.struct_class = UnionAlignment8Lh
        self.src_filename = 'src/UNION_ALIGNMENT8_LH.bin'
