# Autogenerated from KST: please remove this line if doing any edits by hand!

import unittest
from specwrite.common_spec import CommonSpec

from testwrite.union_alignment4_lh import UnionAlignment4Lh

class TestUnionAlignment4Lh(CommonSpec.Base):
    def __init__(self, *args, **kwargs):
        super(TestUnionAlignment4Lh, self).__init__(*args, **kwargs)
        self.struct_class = UnionAlignment4Lh
        self.src_filename = 'src/UNION_ALIGNMENT4_LH.bin'
