# Autogenerated from KST: please remove this line if doing any edits by hand!

import unittest
from specwrite.common_spec import CommonSpec

from testwrite.union_alignment1_arr_d1_lh import UnionAlignment1ArrD1Lh

class TestUnionAlignment1ArrD1Lh(CommonSpec.Base):
    def __init__(self, *args, **kwargs):
        super(TestUnionAlignment1ArrD1Lh, self).__init__(*args, **kwargs)
        self.struct_class = UnionAlignment1ArrD1Lh
        self.src_filename = 'src/UNION_ALIGNMENT1_ARR_D1_LH.bin'
