# Autogenerated from KST: please remove this line if doing any edits by hand!

import unittest
from specwrite.common_spec import CommonSpec

from testwrite.union_alignment2_arr_d1_e1_lh import UnionAlignment2ArrD1E1Lh

class TestUnionAlignment2ArrD1E1Lh(CommonSpec.Base):
    def __init__(self, *args, **kwargs):
        super(TestUnionAlignment2ArrD1E1Lh, self).__init__(*args, **kwargs)
        self.struct_class = UnionAlignment2ArrD1E1Lh
        self.src_filename = 'src/UNION_ALIGNMENT2_ARR_D1_E1_LH.bin'
