# Autogenerated from KST: please remove this line if doing any edits by hand!

import unittest
from specwrite.common_spec import CommonSpec

from testwrite.union_alignment2_arr_d3_lh import UnionAlignment2ArrD3Lh

class TestUnionAlignment2ArrD3Lh(CommonSpec.Base):
    def __init__(self, *args, **kwargs):
        super(TestUnionAlignment2ArrD3Lh, self).__init__(*args, **kwargs)
        self.struct_class = UnionAlignment2ArrD3Lh
        self.src_filename = 'src/UNION_ALIGNMENT2_ARR_D3_LH.bin'
