# Autogenerated from KST: please remove this line if doing any edits by hand!

import unittest
from specwrite.common_spec import CommonSpec

from testwrite.union_alignment1_lh import UnionAlignment1Lh

class TestUnionAlignment1Lh(CommonSpec.Base):
    def __init__(self, *args, **kwargs):
        super(TestUnionAlignment1Lh, self).__init__(*args, **kwargs)
        self.struct_class = UnionAlignment1Lh
        self.src_filename = 'src/UNION_ALIGNMENT1_LH.bin'
