# Autogenerated from KST: please remove this line if doing any edits by hand!

import unittest
from specwrite.common_spec import CommonSpec

from testwrite.union_alignment2_lh import UnionAlignment2Lh

class TestUnionAlignment2Lh(CommonSpec.Base):
    def __init__(self, *args, **kwargs):
        super(TestUnionAlignment2Lh, self).__init__(*args, **kwargs)
        self.struct_class = UnionAlignment2Lh
        self.src_filename = 'src/UNION_ALIGNMENT2_LH.bin'
