# Autogenerated from KST: please remove this line if doing any edits by hand!

import unittest
from specwrite.common_spec import CommonSpec

from testwrite.union_alignment8_arr_d3_e1_lh import UnionAlignment8ArrD3E1Lh

class TestUnionAlignment8ArrD3E1Lh(CommonSpec.Base):
    def __init__(self, *args, **kwargs):
        super(TestUnionAlignment8ArrD3E1Lh, self).__init__(*args, **kwargs)
        self.struct_class = UnionAlignment8ArrD3E1Lh
        self.src_filename = 'src/UNION_ALIGNMENT8_ARR_D3_E1_LH.bin'
