# Autogenerated from KST: please remove this line if doing any edits by hand!

import unittest
from testformats.union_alignment2_arr_d1_lh import UnionAlignment2ArrD1Lh

class TestUnionAlignment2ArrD1Lh(unittest.TestCase):
    def test_union_alignment2_arr_d1_lh(self):
        with UnionAlignment2ArrD1Lh.from_file('src/UNION_ALIGNMENT2_ARR_D1_LH.bin') as r:
            self.assertEqual(r.v.v[0].a_bool.v, True)
            self.assertEqual(r.v.v[0].words.v[0], 1)
            self.assertEqual(r.v.v[0].words.v[1], 0)
            self.assertEqual(r.v.v[1].a_bool.v, False)
            self.assertEqual(r.v.v[1].words.v[0], 2)
            self.assertEqual(r.v.v[1].words.v[1], 0)
            self.assertEqual(r.v.v[2].a_bool.v, True)
            self.assertEqual(r.v.v[2].words.v[0], 3)
            self.assertEqual(r.v.v[2].words.v[1], 8)
