# Autogenerated from KST: please remove this line if doing any edits by hand!

import unittest
from testformats.union_alignment1_lh import UnionAlignment1Lh

class TestUnionAlignment1Lh(unittest.TestCase):
    def test_union_alignment1_lh(self):
        with UnionAlignment1Lh.from_file('src/UNION_ALIGNMENT1_LH.bin') as r:
            self.assertEqual(r.v.bytes.v[0], 0)
            self.assertEqual(r.v.bytes.v[1], 1)
            self.assertEqual(r.v.bytes.v[2], 2)
            self.assertEqual(r.v.bytes.v[3], 3)
