# Autogenerated from KST: please remove this line if doing any edits by hand!

import unittest
from testformats.union_alignment4_arr_d2_e1_lh import UnionAlignment4ArrD2E1Lh

class TestUnionAlignment4ArrD2E1Lh(unittest.TestCase):
    def test_union_alignment4_arr_d2_e1_lh(self):
        with UnionAlignment4ArrD2E1Lh.from_file('src/UNION_ALIGNMENT4_ARR_D2_E1_LH.bin') as r:
            self.assertEqual(r.v.v[0].v[0].bytes.v[0], 1)
            self.assertEqual(r.v.v[0].v[0].bytes.v[1], 0)
            self.assertEqual(r.v.v[0].v[0].bytes.v[2], 0)
            self.assertEqual(r.v.v[0].v[0].bytes.v[3], 0)
            self.assertEqual(r.v.v[0].v[0].dwords.v[0], 1)
            self.assertEqual(r.v.v[0].v[0].dwords.v[1], 2)
