# Autogenerated from KST: please remove this line if doing any edits by hand!

import unittest
from testformats.union_alignment2_arr_d2_e1_lh import UnionAlignment2ArrD2E1Lh

class TestUnionAlignment2ArrD2E1Lh(unittest.TestCase):
    def test_union_alignment2_arr_d2_e1_lh(self):
        with UnionAlignment2ArrD2E1Lh.from_file('src/UNION_ALIGNMENT2_ARR_D2_E1_LH.bin') as r:
            self.assertEqual(r.v.v[0].v[0].a_bool.v, True)
            self.assertEqual(r.v.v[0].v[0].words.v[0], 1)
            self.assertEqual(r.v.v[0].v[0].words.v[1], 0)
