# Autogenerated from KST: please remove this line if doing any edits by hand!

import unittest
from testformats.union_alignment2_lh import UnionAlignment2Lh

class TestUnionAlignment2Lh(unittest.TestCase):
    def test_union_alignment2_lh(self):
        with UnionAlignment2Lh.from_file('src/UNION_ALIGNMENT2_LH.bin') as r:
            self.assertEqual(r.v.a_bool.v, True)
            self.assertEqual(r.v.words.v[0], 1)
            self.assertEqual(r.v.words.v[1], 0)
