# Autogenerated from KST: please remove this line if doing any edits by hand!

import unittest
from testformats.union_alignment8_lh import UnionAlignment8Lh

class TestUnionAlignment8Lh(unittest.TestCase):
    def test_union_alignment8_lh(self):
        with UnionAlignment8Lh.from_file('src/UNION_ALIGNMENT8_LH.bin') as r:
            self.assertEqual(r.v.words.v[0], 1)
            self.assertEqual(r.v.words.v[1], 0)
            self.assertEqual(r.v.words.v[2], 0)
            self.assertEqual(r.v.words.v[3], 0)
            self.assertEqual(r.v.a_lword.v, 1)
