# Autogenerated from KST: please remove this line if doing any edits by hand!

import unittest
from testformats.union_alignment1_arr_d1_lh import UnionAlignment1ArrD1Lh

class TestUnionAlignment1ArrD1Lh(unittest.TestCase):
    def test_union_alignment1_arr_d1_lh(self):
        with UnionAlignment1ArrD1Lh.from_file('src/UNION_ALIGNMENT1_ARR_D1_LH.bin') as r:
            self.assertEqual(r.v.v[0].bytes.v[0], 0)
            self.assertEqual(r.v.v[0].bytes.v[1], 1)
            self.assertEqual(r.v.v[0].bytes.v[2], 2)
            self.assertEqual(r.v.v[0].bytes.v[3], 3)
            self.assertEqual(r.v.v[1].bytes.v[0], 5)
            self.assertEqual(r.v.v[1].bytes.v[1], 6)
            self.assertEqual(r.v.v[1].bytes.v[2], 7)
            self.assertEqual(r.v.v[1].bytes.v[3], 8)
            self.assertEqual(r.v.v[2].bytes.v[0], 9)
            self.assertEqual(r.v.v[2].bytes.v[1], 10)
            self.assertEqual(r.v.v[2].bytes.v[2], 11)
            self.assertEqual(r.v.v[2].bytes.v[3], 12)
