# Autogenerated from KST: please remove this line if doing any edits by hand!

import unittest
from testformats.union_alignment8_arr_d2_e1_lh import UnionAlignment8ArrD2E1Lh

class TestUnionAlignment8ArrD2E1Lh(unittest.TestCase):
    def test_union_alignment8_arr_d2_e1_lh(self):
        with UnionAlignment8ArrD2E1Lh.from_file('src/UNION_ALIGNMENT8_ARR_D2_E1_LH.bin') as r:
            self.assertEqual(r.v.v[0].v[0].words.v[0], 1)
            self.assertEqual(r.v.v[0].v[0].words.v[1], 0)
            self.assertEqual(r.v.v[0].v[0].words.v[2], 0)
            self.assertEqual(r.v.v[0].v[0].words.v[3], 0)
            self.assertEqual(r.v.v[0].v[0].a_lword.v, 1)
