# Autogenerated from KST: please remove this line if doing any edits by hand!

import unittest
from testformats.union_alignment2_arr_d2_lh import UnionAlignment2ArrD2Lh

class TestUnionAlignment2ArrD2Lh(unittest.TestCase):
    def test_union_alignment2_arr_d2_lh(self):
        with UnionAlignment2ArrD2Lh.from_file('src/UNION_ALIGNMENT2_ARR_D2_LH.bin') as r:
            self.assertEqual(r.v.v[0].v[0].a_bool.v, True)
            self.assertEqual(r.v.v[0].v[0].words.v[0], 1)
            self.assertEqual(r.v.v[0].v[0].words.v[1], 0)
            self.assertEqual(r.v.v[0].v[1].a_bool.v, False)
            self.assertEqual(r.v.v[0].v[1].words.v[0], 2)
            self.assertEqual(r.v.v[0].v[1].words.v[1], 0)
            self.assertEqual(r.v.v[0].v[2].a_bool.v, True)
            self.assertEqual(r.v.v[0].v[2].words.v[0], 3)
            self.assertEqual(r.v.v[0].v[2].words.v[1], 8)
            self.assertEqual(r.v.v[1].v[0].a_bool.v, False)
            self.assertEqual(r.v.v[1].v[0].words.v[0], 4)
            self.assertEqual(r.v.v[1].v[0].words.v[1], 0)
            self.assertEqual(r.v.v[1].v[1].a_bool.v, True)
            self.assertEqual(r.v.v[1].v[1].words.v[0], 5)
            self.assertEqual(r.v.v[1].v[1].words.v[1], 0)
            self.assertEqual(r.v.v[1].v[2].a_bool.v, False)
            self.assertEqual(r.v.v[1].v[2].words.v[0], 6)
            self.assertEqual(r.v.v[1].v[2].words.v[1], 16)
            self.assertEqual(r.v.v[2].v[0].a_bool.v, True)
            self.assertEqual(r.v.v[2].v[0].words.v[0], 7)
            self.assertEqual(r.v.v[2].v[0].words.v[1], 0)
            self.assertEqual(r.v.v[2].v[1].a_bool.v, False)
            self.assertEqual(r.v.v[2].v[1].words.v[0], 8)
            self.assertEqual(r.v.v[2].v[1].words.v[1], 0)
            self.assertEqual(r.v.v[2].v[2].a_bool.v, True)
            self.assertEqual(r.v.v[2].v[2].words.v[0], 9)
            self.assertEqual(r.v.v[2].v[2].words.v[1], 32)
