# Autogenerated from KST: please remove this line if doing any edits by hand!

import unittest
from testformats.union_alignment4_lh import UnionAlignment4Lh

class TestUnionAlignment4Lh(unittest.TestCase):
    def test_union_alignment4_lh(self):
        with UnionAlignment4Lh.from_file('src/UNION_ALIGNMENT4_LH.bin') as r:
            self.assertEqual(r.v.bytes.v[0], 1)
            self.assertEqual(r.v.bytes.v[1], 0)
            self.assertEqual(r.v.bytes.v[2], 0)
            self.assertEqual(r.v.bytes.v[3], 0)
            self.assertEqual(r.v.dwords.v[0], 1)
            self.assertEqual(r.v.dwords.v[1], 2)
