# Autogenerated from KST: please remove this line if doing any edits by hand!

import unittest
from testformats.uint_arr_d2_e1_lh import UintArrD2E1Lh

class TestUintArrD2E1Lh(unittest.TestCase):
    def test_uint_arr_d2_e1_lh(self):
        with UintArrD2E1Lh.from_file('src/UINT_ARR_D2_E1_LH.bin') as r:
            self.assertEqual(r.v.v[0].v[0], 1)
