# Autogenerated from KST: please remove this line if doing any edits by hand!

import unittest
from testformats.lint_arr_d2_e1_lh import LintArrD2E1Lh

class TestLintArrD2E1Lh(unittest.TestCase):
    def test_lint_arr_d2_e1_lh(self):
        with LintArrD2E1Lh.from_file('src/LINT_ARR_D2_E1_LH.bin') as r:
            self.assertEqual(r.v.v[0].v[0], -1)
