# Autogenerated from KST: please remove this line if doing any edits by hand!

import unittest
from testformats.byte_arr_d3_e1_lh import ByteArrD3E1Lh

class TestByteArrD3E1Lh(unittest.TestCase):
    def test_byte_arr_d3_e1_lh(self):
        with ByteArrD3E1Lh.from_file('src/BYTE_ARR_D3_E1_LH.bin') as r:
            self.assertEqual(r.v.v[0].v[0].v[0], 1)
