# Autogenerated from KST: please remove this line if doing any edits by hand!

import unittest
from testformats.ulint_arr_d2_lh import UlintArrD2Lh

class TestUlintArrD2Lh(unittest.TestCase):
    def test_ulint_arr_d2_lh(self):
        with UlintArrD2Lh.from_file('src/ULINT_ARR_D2_LH.bin') as r:
            self.assertEqual(r.v.v[0].v[0], 0)
            self.assertEqual(r.v.v[0].v[1], 1)
            self.assertEqual(r.v.v[0].v[2], 2)
            self.assertEqual(r.v.v[1].v[0], 3)
            self.assertEqual(r.v.v[1].v[1], 4)
            self.assertEqual(r.v.v[1].v[2], 5)
            self.assertEqual(r.v.v[2].v[0], 6)
            self.assertEqual(r.v.v[2].v[1], 7)
            self.assertEqual(r.v.v[2].v[2], 8)
