# Autogenerated from KST: please remove this line if doing any edits by hand!

import unittest
from testformats.uint_arr_d1_e1_lh import UintArrD1E1Lh

class TestUintArrD1E1Lh(unittest.TestCase):
    def test_uint_arr_d1_e1_lh(self):
        with UintArrD1E1Lh.from_file('src/UINT_ARR_D1_E1_LH.bin') as r:
            self.assertEqual(r.v.v[0], 1)
