# Autogenerated from KST: please remove this line if doing any edits by hand!

import unittest
from testformats.ulint_arr_d1_e1_lh import UlintArrD1E1Lh

class TestUlintArrD1E1Lh(unittest.TestCase):
    def test_ulint_arr_d1_e1_lh(self):
        with UlintArrD1E1Lh.from_file('src/ULINT_ARR_D1_E1_LH.bin') as r:
            self.assertEqual(r.v.v[0], 1)
