# Autogenerated from KST: please remove this line if doing any edits by hand!

import unittest
from testformats.time_of_day_arr_d3_lh import TimeOfDayArrD3Lh

class TestTimeOfDayArrD3Lh(unittest.TestCase):
    def test_time_of_day_arr_d3_lh(self):
        with TimeOfDayArrD3Lh.from_file('src/TOD_ARR_D3_LH.bin') as r:
            self.assertEqual(r.v.v[0].v[0].v[0], 0)
            self.assertEqual(r.v.v[0].v[0].v[1], 100)
            self.assertEqual(r.v.v[0].v[0].v[2], 1000)
            self.assertEqual(r.v.v[0].v[1].v[0], 1000000)
            self.assertEqual(r.v.v[0].v[1].v[1], 1000000000)
            self.assertEqual(r.v.v[0].v[1].v[2], 10000000000)
            self.assertEqual(r.v.v[0].v[2].v[0], 60000000000)
            self.assertEqual(r.v.v[0].v[2].v[1], 600000000000)
            self.assertEqual(r.v.v[0].v[2].v[2], 3600000000000)
            self.assertEqual(r.v.v[1].v[0].v[0], 36000000000000)
            self.assertEqual(r.v.v[1].v[0].v[1], 999999900)
            self.assertEqual(r.v.v[1].v[0].v[2], 9000000000)
            self.assertEqual(r.v.v[1].v[1].v[0], 59000000000)
            self.assertEqual(r.v.v[1].v[1].v[1], 540000000000)
            self.assertEqual(r.v.v[1].v[1].v[2], 3540000000000)
            self.assertEqual(r.v.v[1].v[2].v[0], 32400000000000)
            self.assertEqual(r.v.v[1].v[2].v[1], 82800000000000)
            self.assertEqual(r.v.v[1].v[2].v[2], 9999999900)
            self.assertEqual(r.v.v[2].v[0].v[0], 59999999900)
            self.assertEqual(r.v.v[2].v[0].v[1], 599999999900)
            self.assertEqual(r.v.v[2].v[0].v[2], 3599999999900)
            self.assertEqual(r.v.v[2].v[1].v[0], 35999999999900)
            self.assertEqual(r.v.v[2].v[1].v[1], 86399999999900)
            self.assertEqual(r.v.v[2].v[1].v[2], 43199999999900)
            self.assertEqual(r.v.v[2].v[2].v[0], 43200000000000)
            self.assertEqual(r.v.v[2].v[2].v[1], 43200000000100)
            self.assertEqual(r.v.v[2].v[2].v[2], 43200001000000)
