# Autogenerated from KST: please remove this line if doing any edits by hand!

import unittest
from testformats.uint_arr_d2_lh import UintArrD2Lh

class TestUintArrD2Lh(unittest.TestCase):
    def test_uint_arr_d2_lh(self):
        with UintArrD2Lh.from_file('src/UINT_ARR_D2_LH.bin') as r:
            self.assertEqual(r.v.v[0].v[0], 0)
            self.assertEqual(r.v.v[0].v[1], 1)
            self.assertEqual(r.v.v[0].v[2], 2)
            self.assertEqual(r.v.v[1].v[0], 3)
            self.assertEqual(r.v.v[1].v[1], 4)
            self.assertEqual(r.v.v[1].v[2], 5)
            self.assertEqual(r.v.v[2].v[0], 6)
            self.assertEqual(r.v.v[2].v[1], 7)
            self.assertEqual(r.v.v[2].v[2], 8)
