# Autogenerated from KST: please remove this line if doing any edits by hand!

import unittest
from testformats.lreal_arr_d3_e1_lh import LrealArrD3E1Lh

class TestLrealArrD3E1Lh(unittest.TestCase):
    def test_lreal_arr_d3_e1_lh(self):
        with LrealArrD3E1Lh.from_file('src/LREAL_ARR_D3_E1_LH.bin') as r:
            self.assertAlmostEqual(r.v.v[0].v[0].v[0], 1, 6)
