# Autogenerated from KST: please remove this line if doing any edits by hand!

import unittest
from testformats.dword_arr_d1_e1_lh import DwordArrD1E1Lh

class TestDwordArrD1E1Lh(unittest.TestCase):
    def test_dword_arr_d1_e1_lh(self):
        with DwordArrD1E1Lh.from_file('src/DWORD_ARR_D1_E1_LH.bin') as r:
            self.assertEqual(r.v.v[0], 1)
