# Autogenerated from KST: please remove this line if doing any edits by hand!

import unittest
from testformats.date_and_time_arr_d1_e1_lh import DateAndTimeArrD1E1Lh

class TestDateAndTimeArrD1E1Lh(unittest.TestCase):
    def test_date_and_time_arr_d1_e1_lh(self):
        with DateAndTimeArrD1E1Lh.from_file('src/DT_ARR_D1_E1_LH.bin') as r:
            self.assertEqual(r.v.v[0], 100)
