# Autogenerated from KST: please remove this line if doing any edits by hand!

import unittest
from testformats.usint_arr_d2_e1_lh import UsintArrD2E1Lh

class TestUsintArrD2E1Lh(unittest.TestCase):
    def test_usint_arr_d2_e1_lh(self):
        with UsintArrD2E1Lh.from_file('src/USINT_ARR_D2_E1_LH.bin') as r:
            self.assertEqual(r.v.v[0].v[0], 1)
