# Autogenerated from KST: please remove this line if doing any edits by hand!

import unittest
from testformats.word_arr_d2_e1_lh import WordArrD2E1Lh

class TestWordArrD2E1Lh(unittest.TestCase):
    def test_word_arr_d2_e1_lh(self):
        with WordArrD2E1Lh.from_file('src/WORD_ARR_D2_E1_LH.bin') as r:
            self.assertEqual(r.v.v[0].v[0], 1)
