# Autogenerated from KST: please remove this line if doing any edits by hand!

import unittest
from testformats.lword_arr_d1_e1_lh import LwordArrD1E1Lh

class TestLwordArrD1E1Lh(unittest.TestCase):
    def test_lword_arr_d1_e1_lh(self):
        with LwordArrD1E1Lh.from_file('src/LWORD_ARR_D1_E1_LH.bin') as r:
            self.assertEqual(r.v.v[0], 1)
