# Autogenerated from KST: please remove this line if doing any edits by hand!

import unittest
from testformats.sint_arr_d1_lh import SintArrD1Lh

class TestSintArrD1Lh(unittest.TestCase):
    def test_sint_arr_d1_lh(self):
        with SintArrD1Lh.from_file('src/SINT_ARR_D1_LH.bin') as r:
            self.assertEqual(r.v.v[0], 0)
            self.assertEqual(r.v.v[1], -1)
            self.assertEqual(r.v.v[2], 2)
