# Autogenerated from KST: please remove this line if doing any edits by hand!

import unittest
from testformats.dint_arr_d3_e1_lh import DintArrD3E1Lh

class TestDintArrD3E1Lh(unittest.TestCase):
    def test_dint_arr_d3_e1_lh(self):
        with DintArrD3E1Lh.from_file('src/DINT_ARR_D3_E1_LH.bin') as r:
            self.assertEqual(r.v.v[0].v[0].v[0], -1)
