# Autogenerated from KST: please remove this line if doing any edits by hand!

import unittest
from testformats.time_arr_d3_e1_lh import TimeArrD3E1Lh

class TestTimeArrD3E1Lh(unittest.TestCase):
    def test_time_arr_d3_e1_lh(self):
        with TimeArrD3E1Lh.from_file('src/TIME_ARR_D3_E1_LH.bin') as r:
            self.assertEqual(r.v.v[0].v[0].v[0], 100)
