# Autogenerated from KST: please remove this line if doing any edits by hand!

import unittest
from testformats.lint_arr_d1_lh import LintArrD1Lh

class TestLintArrD1Lh(unittest.TestCase):
    def test_lint_arr_d1_lh(self):
        with LintArrD1Lh.from_file('src/LINT_ARR_D1_LH.bin') as r:
            self.assertEqual(r.v.v[0], 0)
            self.assertEqual(r.v.v[1], -1)
            self.assertEqual(r.v.v[2], 2)
