# Autogenerated from KST: please remove this line if doing any edits by hand!

import unittest
from testformats.lword_arr_d3_lh import LwordArrD3Lh

class TestLwordArrD3Lh(unittest.TestCase):
    def test_lword_arr_d3_lh(self):
        with LwordArrD3Lh.from_file('src/LWORD_ARR_D3_LH.bin') as r:
            self.assertEqual(r.v.v[0].v[0].v[0], 0)
            self.assertEqual(r.v.v[0].v[0].v[1], 1)
            self.assertEqual(r.v.v[0].v[0].v[2], 2)
            self.assertEqual(r.v.v[0].v[1].v[0], 3)
            self.assertEqual(r.v.v[0].v[1].v[1], 4)
            self.assertEqual(r.v.v[0].v[1].v[2], 5)
            self.assertEqual(r.v.v[0].v[2].v[0], 6)
            self.assertEqual(r.v.v[0].v[2].v[1], 7)
            self.assertEqual(r.v.v[0].v[2].v[2], 8)
            self.assertEqual(r.v.v[1].v[0].v[0], 9)
            self.assertEqual(r.v.v[1].v[0].v[1], 10)
            self.assertEqual(r.v.v[1].v[0].v[2], 11)
            self.assertEqual(r.v.v[1].v[1].v[0], 12)
            self.assertEqual(r.v.v[1].v[1].v[1], 13)
            self.assertEqual(r.v.v[1].v[1].v[2], 14)
            self.assertEqual(r.v.v[1].v[2].v[0], 15)
            self.assertEqual(r.v.v[1].v[2].v[1], 16)
            self.assertEqual(r.v.v[1].v[2].v[2], 17)
            self.assertEqual(r.v.v[2].v[0].v[0], 18)
            self.assertEqual(r.v.v[2].v[0].v[1], 19)
            self.assertEqual(r.v.v[2].v[0].v[2], 20)
            self.assertEqual(r.v.v[2].v[1].v[0], 21)
            self.assertEqual(r.v.v[2].v[1].v[1], 22)
            self.assertEqual(r.v.v[2].v[1].v[2], 23)
            self.assertEqual(r.v.v[2].v[2].v[0], 24)
            self.assertEqual(r.v.v[2].v[2].v[1], 25)
            self.assertEqual(r.v.v[2].v[2].v[2], 26)
