# Autogenerated from KST: please remove this line if doing any edits by hand!

import unittest
from testformats.sint_arr_d3_e1_lh import SintArrD3E1Lh

class TestSintArrD3E1Lh(unittest.TestCase):
    def test_sint_arr_d3_e1_lh(self):
        with SintArrD3E1Lh.from_file('src/SINT_ARR_D3_E1_LH.bin') as r:
            self.assertEqual(r.v.v[0].v[0].v[0], -1)
