# Autogenerated from KST: please remove this line if doing any edits by hand!

import unittest
from testformats.string_3byte_char_by_toarybyte_lh import String3byteCharByToarybyteLh

class TestString3byteCharByToarybyteLh(unittest.TestCase):
    def test_string_3byte_char_by_toarybyte_lh(self):
        with String3byteCharByToarybyteLh.from_file('src/STRING_3BYTE_CHAR_BY_TOARYBYTE_LH.bin') as r:
            self.assertEqual(r.v.v, u"\uff2a\uff30")
