# Autogenerated from KST: please remove this line if doing any edits by hand!

import unittest
from testformats.ulint_arr_d2_e1_lh import UlintArrD2E1Lh

class TestUlintArrD2E1Lh(unittest.TestCase):
    def test_ulint_arr_d2_e1_lh(self):
        with UlintArrD2E1Lh.from_file('src/ULINT_ARR_D2_E1_LH.bin') as r:
            self.assertEqual(r.v.v[0].v[0], 1)
