# Autogenerated from KST: please remove this line if doing any edits by hand!

import unittest
from testformats.byte_arr_d1_e1_lh import ByteArrD1E1Lh

class TestByteArrD1E1Lh(unittest.TestCase):
    def test_byte_arr_d1_e1_lh(self):
        with ByteArrD1E1Lh.from_file('src/BYTE_ARR_D1_E1_LH.bin') as r:
            self.assertEqual(r.v.v[0], 1)
