# Autogenerated from KST: please remove this line if doing any edits by hand!

import unittest
from testformats.date_arr_d3_lh import DateArrD3Lh

class TestDateArrD3Lh(unittest.TestCase):
    def test_date_arr_d3_lh(self):
        with DateArrD3Lh.from_file('src/DATE_ARR_D3_LH.bin') as r:
            self.assertEqual(r.v.v[0].v[0].v[0], 0)
            self.assertEqual(r.v.v[0].v[0].v[1], 777600000000000)
            self.assertEqual(r.v.v[0].v[0].v[2], 2678400000000000)
            self.assertEqual(r.v.v[0].v[1].v[0], 23587200000000000)
            self.assertEqual(r.v.v[0].v[1].v[1], 31536000000000000)
            self.assertEqual(r.v.v[0].v[1].v[2], 315532800000000000)
            self.assertEqual(r.v.v[0].v[2].v[0], 3155760000000000000)
            self.assertEqual(r.v.v[0].v[2].v[1], 2592000000000000)
            self.assertEqual(r.v.v[0].v[2].v[2], 28857600000000000)
            self.assertEqual(r.v.v[1].v[0].v[0], 4291747200000000000)
            self.assertEqual(r.v.v[1].v[0].v[1], 4294857600000000000)
            self.assertEqual(r.v.v[1].v[0].v[2], 946598400000000000)
            self.assertEqual(r.v.v[1].v[1].v[0], 946684800000000000)
            self.assertEqual(r.v.v[1].v[1].v[1], 946771200000000000)
            self.assertEqual(r.v.v[1].v[1].v[2], 2085868800000000000)
            self.assertEqual(r.v.v[1].v[2].v[0], 2085955200000000000)
            self.assertEqual(r.v.v[1].v[2].v[1], 2086041600000000000)
            self.assertEqual(r.v.v[1].v[2].v[2], 31449600000000000)
            self.assertEqual(r.v.v[2].v[0].v[0], 59011200000000000)
            self.assertEqual(r.v.v[2].v[0].v[1], 233366400000000000)
            self.assertEqual(r.v.v[2].v[0].v[2], 626572800000000000)
            self.assertEqual(r.v.v[2].v[1].v[0], 693619200000000000)
            self.assertEqual(r.v.v[2].v[1].v[1], 809222400000000000)
            self.assertEqual(r.v.v[2].v[1].v[2], 863308800000000000)
            self.assertEqual(r.v.v[2].v[2].v[0], 1168300800000000000)
            self.assertEqual(r.v.v[2].v[2].v[1], 1225411200000000000)
            self.assertEqual(r.v.v[2].v[2].v[2], 1669766400000000000)
