# Autogenerated from KST: please remove this line if doing any edits by hand!

import unittest
from testformats.usint_arr_d1_e1_lh import UsintArrD1E1Lh

class TestUsintArrD1E1Lh(unittest.TestCase):
    def test_usint_arr_d1_e1_lh(self):
        with UsintArrD1E1Lh.from_file('src/USINT_ARR_D1_E1_LH.bin') as r:
            self.assertEqual(r.v.v[0], 1)
