# Autogenerated from KST: please remove this line if doing any edits by hand!

import unittest
from testformats.dint_arr_d2_e1_lh import DintArrD2E1Lh

class TestDintArrD2E1Lh(unittest.TestCase):
    def test_dint_arr_d2_e1_lh(self):
        with DintArrD2E1Lh.from_file('src/DINT_ARR_D2_E1_LH.bin') as r:
            self.assertEqual(r.v.v[0].v[0], -1)
