# Autogenerated from KST: please remove this line if doing any edits by hand!

import unittest
from testformats.date_arr_d2_lh import DateArrD2Lh

class TestDateArrD2Lh(unittest.TestCase):
    def test_date_arr_d2_lh(self):
        with DateArrD2Lh.from_file('src/DATE_ARR_D2_LH.bin') as r:
            self.assertEqual(r.v.v[0].v[0], 0)
            self.assertEqual(r.v.v[0].v[1], 777600000000000)
            self.assertEqual(r.v.v[0].v[2], 2678400000000000)
            self.assertEqual(r.v.v[1].v[0], 23587200000000000)
            self.assertEqual(r.v.v[1].v[1], 31536000000000000)
            self.assertEqual(r.v.v[1].v[2], 315532800000000000)
            self.assertEqual(r.v.v[2].v[0], 3155760000000000000)
            self.assertEqual(r.v.v[2].v[1], 2592000000000000)
            self.assertEqual(r.v.v[2].v[2], 28857600000000000)
