# Autogenerated from KST: please remove this line if doing any edits by hand!

import unittest
from testformats.time_of_day_arr_d2_lh import TimeOfDayArrD2Lh

class TestTimeOfDayArrD2Lh(unittest.TestCase):
    def test_time_of_day_arr_d2_lh(self):
        with TimeOfDayArrD2Lh.from_file('src/TOD_ARR_D2_LH.bin') as r:
            self.assertEqual(r.v.v[0].v[0], 0)
            self.assertEqual(r.v.v[0].v[1], 100)
            self.assertEqual(r.v.v[0].v[2], 1000)
            self.assertEqual(r.v.v[1].v[0], 100000)
            self.assertEqual(r.v.v[1].v[1], 1000000000)
            self.assertEqual(r.v.v[1].v[2], 10000000000)
            self.assertEqual(r.v.v[2].v[0], 60000000000)
            self.assertEqual(r.v.v[2].v[1], 600000000000)
            self.assertEqual(r.v.v[2].v[2], 3600000000000)
