# Autogenerated from KST: please remove this line if doing any edits by hand!

import unittest
from testformats.lreal_arr_d3_lh import LrealArrD3Lh

class TestLrealArrD3Lh(unittest.TestCase):
    def test_lreal_arr_d3_lh(self):
        with LrealArrD3Lh.from_file('src/LREAL_ARR_D3_LH.bin') as r:
            self.assertAlmostEqual(r.v.v[0].v[0].v[0], 0, 6)
            self.assertAlmostEqual(r.v.v[0].v[0].v[1], 1, 6)
            self.assertAlmostEqual(r.v.v[0].v[0].v[2], 2, 6)
            self.assertAlmostEqual(r.v.v[0].v[1].v[0], 4, 6)
            self.assertAlmostEqual(r.v.v[0].v[1].v[1], 8, 6)
            self.assertAlmostEqual(r.v.v[0].v[1].v[2], 16, 6)
            self.assertAlmostEqual(r.v.v[0].v[2].v[0], 32, 6)
            self.assertAlmostEqual(r.v.v[0].v[2].v[1], 64, 6)
            self.assertAlmostEqual(r.v.v[0].v[2].v[2], 128, 6)
            self.assertAlmostEqual(r.v.v[1].v[0].v[0], 256, 6)
            self.assertAlmostEqual(r.v.v[1].v[0].v[1], 512, 6)
            self.assertAlmostEqual(r.v.v[1].v[0].v[2], 1024, 6)
            self.assertAlmostEqual(r.v.v[1].v[1].v[0], 2048, 6)
            self.assertAlmostEqual(r.v.v[1].v[1].v[1], 0.5, 6)
            self.assertAlmostEqual(r.v.v[1].v[1].v[2], 0.25, 6)
            self.assertAlmostEqual(r.v.v[1].v[2].v[0], 0.125, 6)
            self.assertAlmostEqual(r.v.v[1].v[2].v[1], 0.0625, 6)
            self.assertAlmostEqual(r.v.v[1].v[2].v[2], 0.03125, 6)
            self.assertAlmostEqual(r.v.v[2].v[0].v[0], 0.015625, 6)
            self.assertAlmostEqual(r.v.v[2].v[0].v[1], 0.0078125, 6)
            self.assertAlmostEqual(r.v.v[2].v[0].v[2], 0.00390625, 6)
            self.assertAlmostEqual(r.v.v[2].v[1].v[0], 0.001953125, 6)
            self.assertAlmostEqual(r.v.v[2].v[1].v[1], 0.0009765625, 6)
            self.assertAlmostEqual(r.v.v[2].v[1].v[2], 0.00048828125, 6)
            self.assertAlmostEqual(r.v.v[2].v[2].v[0], 0.000244140625, 6)
            self.assertAlmostEqual(r.v.v[2].v[2].v[1], -1, 6)
            self.assertAlmostEqual(r.v.v[2].v[2].v[2], -0.5, 6)
