# Autogenerated from KST: please remove this line if doing any edits by hand!

import unittest
from testformats.udint_arr_d3_e1_lh import UdintArrD3E1Lh

class TestUdintArrD3E1Lh(unittest.TestCase):
    def test_udint_arr_d3_e1_lh(self):
        with UdintArrD3E1Lh.from_file('src/UDINT_ARR_D3_E1_LH.bin') as r:
            self.assertEqual(r.v.v[0].v[0].v[0], 1)
