# Autogenerated from KST: please remove this line if doing any edits by hand!

import unittest
from testformats.int_arr_d1_e1_lh import IntArrD1E1Lh

class TestIntArrD1E1Lh(unittest.TestCase):
    def test_int_arr_d1_e1_lh(self):
        with IntArrD1E1Lh.from_file('src/INT_ARR_D1_E1_LH.bin') as r:
            self.assertEqual(r.v.v[0], -1)
