# Autogenerated from KST: please remove this line if doing any edits by hand!

import unittest
from testformats.bool_arr_d2_lh import BoolArrD2Lh

class TestBoolArrD2Lh(unittest.TestCase):
    def test_bool_arr_d2_lh(self):
        with BoolArrD2Lh.from_file('src/BOOL_ARR_D2_LH.bin') as r:
            self.assertEqual(r.instance.v[0].v[0], True)
            self.assertEqual(r.instance.v[0].v[1], False)
            self.assertEqual(r.instance.v[0].v[2], True)
            self.assertEqual(r.instance.v[1].v[0], False)
            self.assertEqual(r.instance.v[1].v[1], True)
            self.assertEqual(r.instance.v[1].v[2], False)
            self.assertEqual(r.instance.v[2].v[0], True)
            self.assertEqual(r.instance.v[2].v[1], False)
            self.assertEqual(r.instance.v[2].v[2], True)
            self.assertEqual(r.instance.block_info.pos_block, 0)
            self.assertEqual(r.instance.block_info.len_block, 2)
            self.assertEqual(r.instance.block_info.pos_data, 0)
            self.assertEqual(r.instance.block_info.ks_type, u"b1")
            self.assertEqual(r.instance.block_info.num_repeat, 9)
            self.assertEqual(r.instance.block_info.len_data, 2)
