# Autogenerated from KST: please remove this line if doing any edits by hand!

import unittest
from testformats.word_arr_d3_e1_lh import WordArrD3E1Lh

class TestWordArrD3E1Lh(unittest.TestCase):
    def test_word_arr_d3_e1_lh(self):
        with WordArrD3E1Lh.from_file('src/WORD_ARR_D3_E1_LH.bin') as r:
            self.assertEqual(r.v.v[0].v[0].v[0], 1)
