# Autogenerated from KST: please remove this line if doing any edits by hand!

import unittest
from testformats.time_arr_d2_e1_lh import TimeArrD2E1Lh

class TestTimeArrD2E1Lh(unittest.TestCase):
    def test_time_arr_d2_e1_lh(self):
        with TimeArrD2E1Lh.from_file('src/TOD_ARR_D2_E1_LH.bin') as r:
            self.assertEqual(r.v.v[0].v[0], 100)
