# Autogenerated from KST: please remove this line if doing any edits by hand!

import unittest
from testformats.date_arr_d1_e1_lh import DateArrD1E1Lh

class TestDateArrD1E1Lh(unittest.TestCase):
    def test_date_arr_d1_e1_lh(self):
        with DateArrD1E1Lh.from_file('src/DATE_ARR_D1_E1_LH.bin') as r:
            self.assertEqual(r.v.v[0], 86400000000000)
