# Autogenerated from KST: please remove this line if doing any edits by hand!

import unittest
from testformats.time_of_day_arr_d1_e1_lh import TimeOfDayArrD1E1Lh

class TestTimeOfDayArrD1E1Lh(unittest.TestCase):
    def test_time_of_day_arr_d1_e1_lh(self):
        with TimeOfDayArrD1E1Lh.from_file('src/TOD_ARR_D1_E1_LH.bin') as r:
            self.assertEqual(r.v.v[0], 100)
