# Autogenerated from KST: please remove this line if doing any edits by hand!

import unittest
from testformats.udint_arr_d1_e1_lh import UdintArrD1E1Lh

class TestUdintArrD1E1Lh(unittest.TestCase):
    def test_udint_arr_d1_e1_lh(self):
        with UdintArrD1E1Lh.from_file('src/UDINT_ARR_D1_E1_LH.bin') as r:
            self.assertEqual(r.v.v[0], 1)
