# Autogenerated from KST: please remove this line if doing any edits by hand!

import unittest
from testformats.lreal_arr_d1_lh import LrealArrD1Lh

class TestLrealArrD1Lh(unittest.TestCase):
    def test_lreal_arr_d1_lh(self):
        with LrealArrD1Lh.from_file('src/LREAL_ARR_D1_LH.bin') as r:
            self.assertAlmostEqual(r.v.v[0], 0, 6)
            self.assertAlmostEqual(r.v.v[1], 1, 6)
            self.assertAlmostEqual(r.v.v[2], 2, 6)
