# Autogenerated from KST: please remove this line if doing any edits by hand!

import unittest
from testformats.udint_arr_d1_lh import UdintArrD1Lh

class TestUdintArrD1Lh(unittest.TestCase):
    def test_udint_arr_d1_lh(self):
        with UdintArrD1Lh.from_file('src/UDINT_ARR_D1_LH.bin') as r:
            self.assertEqual(r.v.v[0], 0)
            self.assertEqual(r.v.v[1], 1)
            self.assertEqual(r.v.v[2], 2)
