# Autogenerated from KST: please remove this line if doing any edits by hand!

import unittest
from testformats.real_arr_d2_e1_lh import RealArrD2E1Lh

class TestRealArrD2E1Lh(unittest.TestCase):
    def test_real_arr_d2_e1_lh(self):
        with RealArrD2E1Lh.from_file('src/REAL_ARR_D2_E1_LH.bin') as r:
            self.assertAlmostEqual(r.v.v[0].v[0], 1, 6)
