# Autogenerated from KST: please remove this line if doing any edits by hand!

import unittest
from testformats.time_arr_d2_lh import TimeArrD2Lh

class TestTimeArrD2Lh(unittest.TestCase):
    def test_time_arr_d2_lh(self):
        with TimeArrD2Lh.from_file('src/TIME_ARR_D2_LH.bin') as r:
            self.assertEqual(r.v.v[0].v[0], 0)
            self.assertEqual(r.v.v[0].v[1], 100)
            self.assertEqual(r.v.v[0].v[2], 9223372036854775800)
            self.assertEqual(r.v.v[1].v[0], 1000)
            self.assertEqual(r.v.v[1].v[1], 1000000)
            self.assertEqual(r.v.v[1].v[2], 60000000000)
            self.assertEqual(r.v.v[2].v[0], 3600000000000)
            self.assertEqual(r.v.v[2].v[1], 86400000000000)
            self.assertEqual(r.v.v[2].v[2], -100)
