# Autogenerated from KST: please remove this line if doing any edits by hand!

import unittest
from testformats.lreal_arr_d2_lh import LrealArrD2Lh

class TestLrealArrD2Lh(unittest.TestCase):
    def test_lreal_arr_d2_lh(self):
        with LrealArrD2Lh.from_file('src/LREAL_ARR_D2_LH.bin') as r:
            self.assertAlmostEqual(r.v.v[0].v[0], 0, 6)
            self.assertAlmostEqual(r.v.v[0].v[1], 1, 6)
            self.assertAlmostEqual(r.v.v[0].v[2], 2, 6)
            self.assertAlmostEqual(r.v.v[1].v[0], 4, 6)
            self.assertAlmostEqual(r.v.v[1].v[1], 8, 6)
            self.assertAlmostEqual(r.v.v[1].v[2], 16, 6)
            self.assertAlmostEqual(r.v.v[2].v[0], 32, 6)
            self.assertAlmostEqual(r.v.v[2].v[1], 64, 6)
            self.assertAlmostEqual(r.v.v[2].v[2], 128, 6)
