# Autogenerated from KST: please remove this line if doing any edits by hand!

import unittest
from testformats.string_n2_by_toarybyte_lh import StringN2ByToarybyteLh

class TestStringN2ByToarybyteLh(unittest.TestCase):
    def test_string_n2_by_toarybyte_lh(self):
        with StringN2ByToarybyteLh.from_file('src/STRING_N2_BY_TOARYBYTE_LH.bin') as r:
            self.assertEqual(r.v.v, u"a")
