# Autogenerated from KST: please remove this line if doing any edits by hand!

import unittest
from testformats.int_arr_d2_e1_lh import IntArrD2E1Lh

class TestIntArrD2E1Lh(unittest.TestCase):
    def test_int_arr_d2_e1_lh(self):
        with IntArrD2E1Lh.from_file('src/INT_ARR_D2_E1_LH.bin') as r:
            self.assertEqual(r.v.v[0].v[0], -1)
