# Autogenerated from KST: please remove this line if doing any edits by hand!

import unittest
from testformats.align import Align

class TestAlign(unittest.TestCase):
    def test_align(self):
        with Align.from_file('src/LWORD_ARR_D3_LH.bin') as r:
            self.assertEqual(r.align2_p0.size, 0)
            self.assertEqual(r.align2_p1.size, 1)
            self.assertEqual(r.align2_p2.size, 0)
            self.assertEqual(r.align4_p0.size, 0)
            self.assertEqual(r.align4_p1.size, 3)
            self.assertEqual(r.align4_p2.size, 2)
            self.assertEqual(r.align4_p3.size, 1)
            self.assertEqual(r.align4_p4.size, 0)
            self.assertEqual(r.align8_p0.size, 0)
            self.assertEqual(r.align8_p1.size, 7)
            self.assertEqual(r.align8_p2.size, 6)
            self.assertEqual(r.align8_p3.size, 5)
            self.assertEqual(r.align8_p4.size, 4)
            self.assertEqual(r.align8_p5.size, 3)
            self.assertEqual(r.align8_p6.size, 2)
            self.assertEqual(r.align8_p7.size, 1)
            self.assertEqual(r.align8_p8.size, 0)
