# Autogenerated from KST: please remove this line if doing any edits by hand!

import unittest
from testformats.date_arr_d1_lh import DateArrD1Lh

class TestDateArrD1Lh(unittest.TestCase):
    def test_date_arr_d1_lh(self):
        with DateArrD1Lh.from_file('src/DATE_ARR_D1_LH.bin') as r:
            self.assertEqual(r.v.v[0], 0)
            self.assertEqual(r.v.v[1], 86400000000000)
            self.assertEqual(r.v.v[2], 1780531200000000000)
