# Autogenerated from KST: please remove this line if doing any edits by hand!

import unittest
from testformats.word_arr_d1_lh import WordArrD1Lh

class TestWordArrD1Lh(unittest.TestCase):
    def test_word_arr_d1_lh(self):
        with WordArrD1Lh.from_file('src/WORD_ARR_D1_LH.bin') as r:
            self.assertEqual(r.v.v[0], 0)
            self.assertEqual(r.v.v[1], 1)
            self.assertEqual(r.v.v[2], 2)
