# Autogenerated from KST: please remove this line if doing any edits by hand!

import unittest
from testformats.real_arr_d1_lh import RealArrD1Lh

class TestRealArrD1Lh(unittest.TestCase):
    def test_real_arr_d1_lh(self):
        with RealArrD1Lh.from_file('src/REAL_ARR_D1_LH.bin') as r:
            self.assertAlmostEqual(r.v.v[0], 0, 6)
            self.assertAlmostEqual(r.v.v[1], 1, 6)
            self.assertAlmostEqual(r.v.v[2], 2, 6)
