# Autogenerated from KST: please remove this line if doing any edits by hand!

import unittest
from testformats.dint_arr_d1_lh import DintArrD1Lh

class TestDintArrD1Lh(unittest.TestCase):
    def test_dint_arr_d1_lh(self):
        with DintArrD1Lh.from_file('src/DINT_ARR_D1_LH.bin') as r:
            self.assertEqual(r.v.v[0], 0)
            self.assertEqual(r.v.v[1], -1)
            self.assertEqual(r.v.v[2], 2)
