# Autogenerated from KST: please remove this line if doing any edits by hand!

import unittest
from testformats.lword_arr_d1_lh import LwordArrD1Lh

class TestLwordArrD1Lh(unittest.TestCase):
    def test_lword_arr_d1_lh(self):
        with LwordArrD1Lh.from_file('src/LWORD_ARR_D1_LH.bin') as r:
            self.assertEqual(r.v.v[0], 0)
            self.assertEqual(r.v.v[1], 1)
            self.assertEqual(r.v.v[2], 2)
