# Autogenerated from KST: please remove this line if doing any edits by hand!

import unittest
from testformats.lreal_arr_d1_e1_lh import LrealArrD1E1Lh

class TestLrealArrD1E1Lh(unittest.TestCase):
    def test_lreal_arr_d1_e1_lh(self):
        with LrealArrD1E1Lh.from_file('src/LREAL_ARR_D1_E1_LH.bin') as r:
            self.assertAlmostEqual(r.v.v[0], 1, 6)
