# Autogenerated from KST: please remove this line if doing any edits by hand!

import unittest
from testformats.sint_arr_d2_e1_lh import SintArrD2E1Lh

class TestSintArrD2E1Lh(unittest.TestCase):
    def test_sint_arr_d2_e1_lh(self):
        with SintArrD2E1Lh.from_file('src/SINT_ARR_D2_E1_LH.bin') as r:
            self.assertEqual(r.v.v[0].v[0], -1)
