# Autogenerated from KST: please remove this line if doing any edits by hand!

import unittest
from testformats.date_and_time_arr_d3_lh import DateAndTimeArrD3Lh

class TestDateAndTimeArrD3Lh(unittest.TestCase):
    def test_date_and_time_arr_d3_lh(self):
        with DateAndTimeArrD3Lh.from_file('src/DT_ARR_D3_LH.bin') as r:
            self.assertEqual(r.v.v[0].v[0].v[0], 0)
            self.assertEqual(r.v.v[0].v[0].v[1], 100)
            self.assertEqual(r.v.v[0].v[0].v[2], 1000)
            self.assertEqual(r.v.v[0].v[1].v[0], 1000000)
            self.assertEqual(r.v.v[0].v[1].v[1], 1000000000)
            self.assertEqual(r.v.v[0].v[1].v[2], 10000000000)
            self.assertEqual(r.v.v[0].v[2].v[0], 60000000000)
            self.assertEqual(r.v.v[0].v[2].v[1], 600000000000)
            self.assertEqual(r.v.v[0].v[2].v[2], 3600000000000)
            self.assertEqual(r.v.v[1].v[0].v[0], 36000000000000)
            self.assertEqual(r.v.v[1].v[0].v[1], 86400000000000)
            self.assertEqual(r.v.v[1].v[0].v[2], 777600000000000)
            self.assertEqual(r.v.v[1].v[1].v[0], 2678400000000000)
            self.assertEqual(r.v.v[1].v[1].v[1], 23587200000000000)
            self.assertEqual(r.v.v[1].v[1].v[2], 31536000000000000)
            self.assertEqual(r.v.v[1].v[2].v[0], 315532800000000000)
            self.assertEqual(r.v.v[1].v[2].v[1], 3155760000000000000)
            self.assertEqual(r.v.v[1].v[2].v[2], 999999900)
            self.assertEqual(r.v.v[2].v[0].v[0], 9999999900)
            self.assertEqual(r.v.v[2].v[0].v[1], 59999999900)
            self.assertEqual(r.v.v[2].v[0].v[2], 599999999900)
            self.assertEqual(r.v.v[2].v[1].v[0], 3599999999900)
            self.assertEqual(r.v.v[2].v[1].v[1], 35999999999900)
            self.assertEqual(r.v.v[2].v[1].v[2], 86399999999900)
            self.assertEqual(r.v.v[2].v[2].v[0], 777599999999900)
            self.assertEqual(r.v.v[2].v[2].v[1], 2678399999999900)
            self.assertEqual(r.v.v[2].v[2].v[2], 23587199999999900)
