# Autogenerated from KST: please remove this line if doing any edits by hand!

import unittest
from testformats.real_arr_d3_e1_lh import RealArrD3E1Lh

class TestRealArrD3E1Lh(unittest.TestCase):
    def test_real_arr_d3_e1_lh(self):
        with RealArrD3E1Lh.from_file('src/REAL_ARR_D3_E1_LH.bin') as r:
            self.assertAlmostEqual(r.v.v[0].v[0].v[0], 1, 6)
