# Autogenerated from KST: please remove this line if doing any edits by hand!

import unittest
from testformats.word_arr_d1_e1_lh import WordArrD1E1Lh

class TestWordArrD1E1Lh(unittest.TestCase):
    def test_word_arr_d1_e1_lh(self):
        with WordArrD1E1Lh.from_file('src/WORD_ARR_D1_E1_LH.bin') as r:
            self.assertEqual(r.v.v[0], 1)
