# Autogenerated from KST: please remove this line if doing any edits by hand!

import unittest
from testformats.uint_arr_d3_lh import UintArrD3Lh

class TestUintArrD3Lh(unittest.TestCase):
    def test_uint_arr_d3_lh(self):
        with UintArrD3Lh.from_file('src/UINT_ARR_D3_E1_LH.bin') as r:
            self.assertEqual(r.v.v[0].v[0].v[0], 1)
