# Autogenerated from KST: please remove this line if doing any edits by hand!

import unittest
from testformats.sint_arr_d1_e1_lh import SintArrD1E1Lh

class TestSintArrD1E1Lh(unittest.TestCase):
    def test_sint_arr_d1_e1_lh(self):
        with SintArrD1E1Lh.from_file('src/SINT_ARR_D1_E1_LH.bin') as r:
            self.assertEqual(r.v.v[0], -1)
