# Autogenerated from KST: please remove this line if doing any edits by hand!

import unittest
from testformats.uint_arr_d1_lh import UintArrD1Lh

class TestUintArrD1Lh(unittest.TestCase):
    def test_uint_arr_d1_lh(self):
        with UintArrD1Lh.from_file('src/UINT_ARR_D1_LH.bin') as r:
            self.assertEqual(r.v.v[0], 0)
            self.assertEqual(r.v.v[1], 1)
            self.assertEqual(r.v.v[2], 2)
