# Autogenerated from KST: please remove this line if doing any edits by hand!

import unittest
from testformats.real_arr_d1_e1_lh import RealArrD1E1Lh

class TestRealArrD1E1Lh(unittest.TestCase):
    def test_real_arr_d1_e1_lh(self):
        with RealArrD1E1Lh.from_file('src/REAL_ARR_D1_E1_LH.bin') as r:
            self.assertAlmostEqual(r.v.v[0], 1, 6)
