# Autogenerated from KST: please remove this line if doing any edits by hand!

import unittest
from testformats.date_arr_d2_e1_lh import DateArrD2E1Lh

class TestDateArrD2E1Lh(unittest.TestCase):
    def test_date_arr_d2_e1_lh(self):
        with DateArrD2E1Lh.from_file('src/DATE_ARR_D2_E1_LH.bin') as r:
            self.assertEqual(r.v.v[0].v[0], 86400000000000)
