# Autogenerated from KST: please remove this line if doing any edits by hand!

import unittest
from testformats.time_arr_d1_lh import TimeArrD1Lh

class TestTimeArrD1Lh(unittest.TestCase):
    def test_time_arr_d1_lh(self):
        with TimeArrD1Lh.from_file('src/TIME_ARR_D1_LH.bin') as r:
            self.assertEqual(r.v.v[0], 0)
            self.assertEqual(r.v.v[1], 100)
            self.assertEqual(r.v.v[2], 9223372036854775800)
