# Autogenerated from KST: please remove this line if doing any edits by hand!

import unittest
from testformats.time_of_day_arr_d3_e1_lh import TimeOfDayArrD3E1Lh

class TestTimeOfDayArrD3E1Lh(unittest.TestCase):
    def test_time_of_day_arr_d3_e1_lh(self):
        with TimeOfDayArrD3E1Lh.from_file('src/TOD_ARR_D3_E1_LH.bin') as r:
            self.assertEqual(r.v.v[0].v[0].v[0], 100)
