# Autogenerated from KST: please remove this line if doing any edits by hand!

import unittest
from testformats.byte_arr_d2_e1_lh import ByteArrD2E1Lh

class TestByteArrD2E1Lh(unittest.TestCase):
    def test_byte_arr_d2_e1_lh(self):
        with ByteArrD2E1Lh.from_file('src/BYTE_ARR_D2_E1_LH.bin') as r:
            self.assertEqual(r.v.v[0].v[0], 1)
