# Autogenerated from KST: please remove this line if doing any edits by hand!

import unittest
from testformats.byte_arr_d1_lh import ByteArrD1Lh

class TestByteArrD1Lh(unittest.TestCase):
    def test_byte_arr_d1_lh(self):
        with ByteArrD1Lh.from_file('src/BYTE_ARR_D1_LH.bin') as r:
            self.assertEqual(r.v.v[0], 0)
            self.assertEqual(r.v.v[1], 1)
            self.assertEqual(r.v.v[2], 2)
