# Autogenerated from KST: please remove this line if doing any edits by hand!

import unittest
from testformats.lword_arr_d2_e1_lh import LwordArrD2E1Lh

class TestLwordArrD2E1Lh(unittest.TestCase):
    def test_lword_arr_d2_e1_lh(self):
        with LwordArrD2E1Lh.from_file('src/LWORD_ARR_D2_E1_LH.bin') as r:
            self.assertEqual(r.v.v[0].v[0], 1)
