# Autogenerated from KST: please remove this line if doing any edits by hand!

import unittest
from testformats.dword_arr_d1_lh import DwordArrD1Lh

class TestDwordArrD1Lh(unittest.TestCase):
    def test_dword_arr_d1_lh(self):
        with DwordArrD1Lh.from_file('src/DWORD_ARR_D1_LH.bin') as r:
            self.assertEqual(r.v.v[0], 0)
            self.assertEqual(r.v.v[1], 1)
            self.assertEqual(r.v.v[2], 2)
