# Autogenerated from KST: please remove this line if doing any edits by hand!

import unittest
from testformats.string_n16_by_toarybyte_lh import StringN16ByToarybyteLh

class TestStringN16ByToarybyteLh(unittest.TestCase):
    def test_string_n16_by_toarybyte_lh(self):
        with StringN16ByToarybyteLh.from_file('src/STRING_N16_BY_TOARYBYTE_LH.bin') as r:
            self.assertEqual(r.v.v, u"abc")
