# Autogenerated from KST: please remove this line if doing any edits by hand!

import unittest
from testformats.ulint_arr_d1_lh import UlintArrD1Lh

class TestUlintArrD1Lh(unittest.TestCase):
    def test_ulint_arr_d1_lh(self):
        with UlintArrD1Lh.from_file('src/ULINT_ARR_D1_LH.bin') as r:
            self.assertEqual(r.v.v[0], 0)
            self.assertEqual(r.v.v[1], 1)
            self.assertEqual(r.v.v[2], 2)
