# Autogenerated from KST: please remove this line if doing any edits by hand!

import unittest
from testformats.lword_arr_d3_e1_lh import LwordArrD3E1Lh

class TestLwordArrD3E1Lh(unittest.TestCase):
    def test_lword_arr_d3_e1_lh(self):
        with LwordArrD3E1Lh.from_file('src/LWORD_ARR_D3_E1_LH.bin') as r:
            self.assertEqual(r.v.v[0].v[0].v[0], 1)
