# Autogenerated from KST: please remove this line if doing any edits by hand!

import unittest
from testformats.string_2byte_char_by_toarybyte_lh import String2byteCharByToarybyteLh

class TestString2byteCharByToarybyteLh(unittest.TestCase):
    def test_string_2byte_char_by_toarybyte_lh(self):
        with String2byteCharByToarybyteLh.from_file('src/STRING_2BYTE_CHAR_BY_TOARYBYTE_LH.bin') as r:
            self.assertEqual(r.v.v, u"\u03a3-\u03b4")
