# Autogenerated from KST: please remove this line if doing any edits by hand!

import unittest
from testformats.dint_arr_d1_e1_lh import DintArrD1E1Lh

class TestDintArrD1E1Lh(unittest.TestCase):
    def test_dint_arr_d1_e1_lh(self):
        with DintArrD1E1Lh.from_file('src/DINT_ARR_D1_E1_LH.bin') as r:
            self.assertEqual(r.v.v[0], -1)
