# Autogenerated from KST: please remove this line if doing any edits by hand!

import unittest
from testformats.usint_arr_d3_e1_lh import UsintArrD3E1Lh

class TestUsintArrD3E1Lh(unittest.TestCase):
    def test_usint_arr_d3_e1_lh(self):
        with UsintArrD3E1Lh.from_file('src/USINT_ARR_D3_E1_LH.bin') as r:
            self.assertEqual(r.v.v[0].v[0].v[0], 1)
