# Autogenerated from KST: please remove this line if doing any edits by hand!

import unittest
from testformats.lreal_arr_d2_e1_lh import LrealArrD2E1Lh

class TestLrealArrD2E1Lh(unittest.TestCase):
    def test_lreal_arr_d2_e1_lh(self):
        with LrealArrD2E1Lh.from_file('src/LREAL_ARR_D2_E1_LH.bin') as r:
            self.assertAlmostEqual(r.v.v[0].v[0], 1, 6)
