# Autogenerated from KST: please remove this line if doing any edits by hand!

import unittest
from testformats.string_4byte_char_by_toarybyte_lh import String4byteCharByToarybyteLh

class TestString4byteCharByToarybyteLh(unittest.TestCase):
    def test_string_4byte_char_by_toarybyte_lh(self):
        with String4byteCharByToarybyteLh.from_file('src/STRING_4BYTE_CHAR_BY_TOARYBYTE_LH.bin') as r:
            self.assertEqual(r.raw, b"\xF0\x9F\x92\xAF")
