# Autogenerated from KST: please remove this line if doing any edits by hand!

import unittest
from testformats.time_of_day_arr_d1_lh import TimeOfDayArrD1Lh

class TestTimeOfDayArrD1Lh(unittest.TestCase):
    def test_time_of_day_arr_d1_lh(self):
        with TimeOfDayArrD1Lh.from_file('src/TOD_ARR_D1_LH.bin') as r:
            self.assertEqual(r.v.v[0], 0)
            self.assertEqual(r.v.v[1], 100)
            self.assertEqual(r.v.v[2], 86399999999900)
