# Autogenerated from KST: please remove this line if doing any edits by hand!

import unittest
from testformats.date_and_time_arr_d3_e1_lh import DateAndTimeArrD3E1Lh

class TestDateAndTimeArrD3E1Lh(unittest.TestCase):
    def test_date_and_time_arr_d3_e1_lh(self):
        with DateAndTimeArrD3E1Lh.from_file('src/DT_ARR_D3_E1_LH.bin') as r:
            self.assertEqual(r.v.v[0].v[0].v[0], 100)
