# Autogenerated from KST: please remove this line if doing any edits by hand!

import unittest
from testformats.date_and_time_arr_d1_lh import DateAndTimeArrD1Lh

class TestDateAndTimeArrD1Lh(unittest.TestCase):
    def test_date_and_time_arr_d1_lh(self):
        with DateAndTimeArrD1Lh.from_file('src/DT_ARR_D1_LH.bin') as r:
            self.assertEqual(r.v.v[0], 0)
            self.assertEqual(r.v.v[1], 100)
            self.assertEqual(r.v.v[2], 1780563600000000000)
