# Autogenerated from KST: please remove this line if doing any edits by hand!

import unittest
from testformats.time_arr_d3_lh import TimeArrD3Lh

class TestTimeArrD3Lh(unittest.TestCase):
    def test_time_arr_d3_lh(self):
        with TimeArrD3Lh.from_file('src/TIME_ARR_D3_LH.bin') as r:
            self.assertEqual(r.v.v[0].v[0].v[0], 0)
            self.assertEqual(r.v.v[0].v[0].v[1], 100)
            self.assertEqual(r.v.v[0].v[0].v[2], 9223372036854775800)
            self.assertEqual(r.v.v[0].v[1].v[0], 1000)
            self.assertEqual(r.v.v[0].v[1].v[1], 1000000)
            self.assertEqual(r.v.v[0].v[1].v[2], 60000000000)
            self.assertEqual(r.v.v[0].v[2].v[0], 3600000000000)
            self.assertEqual(r.v.v[0].v[2].v[1], 86400000000000)
            self.assertEqual(r.v.v[0].v[2].v[2], -100)
            self.assertEqual(r.v.v[1].v[0].v[0], -9223372036854775800)
            self.assertEqual(r.v.v[1].v[0].v[1], -1000)
            self.assertEqual(r.v.v[1].v[0].v[2], -1000000)
            self.assertEqual(r.v.v[1].v[1].v[0], -60000000000)
            self.assertEqual(r.v.v[1].v[1].v[1], -3600000000000)
            self.assertEqual(r.v.v[1].v[1].v[2], -86400000000000)
            self.assertEqual(r.v.v[1].v[2].v[0], 999900)
            self.assertEqual(r.v.v[1].v[2].v[1], 999000000)
            self.assertEqual(r.v.v[1].v[2].v[2], 59000000000)
            self.assertEqual(r.v.v[2].v[0].v[0], 3540000000000)
            self.assertEqual(r.v.v[2].v[0].v[1], 82800000000000)
            self.assertEqual(r.v.v[2].v[0].v[2], 8639913600000000000)
            self.assertEqual(r.v.v[2].v[1].v[0], -999900)
            self.assertEqual(r.v.v[2].v[1].v[1], -999000000)
            self.assertEqual(r.v.v[2].v[1].v[2], -59000000000)
            self.assertEqual(r.v.v[2].v[2].v[0], -3540000000000)
            self.assertEqual(r.v.v[2].v[2].v[1], -82800000000000)
            self.assertEqual(r.v.v[2].v[2].v[2], -8639913600000000000)
