# Autogenerated from KST: please remove this line if doing any edits by hand!

import unittest
from testformats.struct_small_lh import StructSmallLh

class TestStructSmallLh(unittest.TestCase):
    def test_struct_small_lh(self):
        with StructSmallLh.from_file('src/STRUCT_SMALL_LH.bin') as r:
            self.assertEqual(r.v.s.v, u"a")
            self.assertEqual(r.v.u.v, 1)
