# Autogenerated from KST: please remove this line if doing any edits by hand!

import unittest
from testformats.struct_small_arr_d1_lh import StructSmallArrD1Lh

class TestStructSmallArrD1Lh(unittest.TestCase):
    def test_struct_small_arr_d1_lh(self):
        with StructSmallArrD1Lh.from_file('src/STRUCT_SMALL_ARR_D1_LH.bin') as r:
            self.assertEqual(r.v.v[0].s.v, u"a")
            self.assertEqual(r.v.v[0].u.v, 1)
            self.assertEqual(r.v.v[1].s.v, u"b")
            self.assertEqual(r.v.v[1].u.v, 2)
            self.assertEqual(r.v.v[2].s.v, u"c")
            self.assertEqual(r.v.v[2].u.v, 3)
