# Autogenerated from KST: please remove this line if doing any edits by hand!

import unittest
from testformats.struct_small_arr_d3_e1_lh import StructSmallArrD3E1Lh

class TestStructSmallArrD3E1Lh(unittest.TestCase):
    def test_struct_small_arr_d3_e1_lh(self):
        with StructSmallArrD3E1Lh.from_file('src/STRUCT_SMALL_ARR_D3_E1_LH.bin') as r:
            self.assertEqual(r.v.v[0].v[0].v[0].s.v, u"a")
            self.assertEqual(r.v.v[0].v[0].v[0].u.v, 1)
