# Autogenerated from KST: please remove this line if doing any edits by hand!

import unittest
from testformats.struct_padded_arr_d1_lh import StructPaddedArrD1Lh

class TestStructPaddedArrD1Lh(unittest.TestCase):
    def test_struct_padded_arr_d1_lh(self):
        with StructPaddedArrD1Lh.from_file('src/STRUCT_PADDED_ARR_D1_LH.bin') as r:
            self.assertEqual(r.v.v[0].a_usint.v, 1)
            self.assertEqual(r.v.v[0].a_uint.v, 2)
            self.assertEqual(r.v.v[0].a_sint.v, -3)
            self.assertEqual(r.v.v[0].a_dint.v, -4)
            self.assertEqual(r.v.v[0].a_ulint.v, 5)
            self.assertEqual(r.v.v[0].a_bool.v, True)
            self.assertEqual(r.v.v[1].a_usint.v, 6)
            self.assertEqual(r.v.v[1].a_uint.v, 7)
            self.assertEqual(r.v.v[1].a_sint.v, -8)
            self.assertEqual(r.v.v[1].a_dint.v, -9)
            self.assertEqual(r.v.v[1].a_ulint.v, 10)
            self.assertEqual(r.v.v[1].a_bool.v, False)
            self.assertEqual(r.v.v[2].a_usint.v, 11)
            self.assertEqual(r.v.v[2].a_uint.v, 12)
            self.assertEqual(r.v.v[2].a_sint.v, -13)
            self.assertEqual(r.v.v[2].a_dint.v, -14)
            self.assertEqual(r.v.v[2].a_ulint.v, 15)
            self.assertEqual(r.v.v[2].a_bool.v, True)
