# Autogenerated from KST: please remove this line if doing any edits by hand!

import unittest
from testformats.struct_alignment1 import StructAlignment1

class TestStructAlignment1(unittest.TestCase):
    def test_struct_alignment1(self):
        with StructAlignment1.from_file('src/STRUCT_ALIGNMENT1.bin') as r:
            self.assertEqual(r.v.a_usint.v, 2)
            self.assertEqual(r.v.a_sint.v, -1)
            self.assertEqual(r.v.bytes.v[0], 3)
            self.assertEqual(r.v.bytes.v[1], 4)
