# Autogenerated from KST: please remove this line if doing any edits by hand!

import unittest
from testformats.struct_padded_arr_d2_e1_lh import StructPaddedArrD2E1Lh

class TestStructPaddedArrD2E1Lh(unittest.TestCase):
    def test_struct_padded_arr_d2_e1_lh(self):
        with StructPaddedArrD2E1Lh.from_file('src/STRUCT_PADDED_ARR_D2_E1_LH.bin') as r:
            self.assertEqual(r.v.v[0].v[0].a_usint.v, 1)
            self.assertEqual(r.v.v[0].v[0].a_uint.v, 2)
            self.assertEqual(r.v.v[0].v[0].a_sint.v, -3)
            self.assertEqual(r.v.v[0].v[0].a_dint.v, -4)
            self.assertEqual(r.v.v[0].v[0].a_ulint.v, 5)
            self.assertEqual(r.v.v[0].v[0].a_bool.v, True)
