# Autogenerated from KST: please remove this line if doing any edits by hand!

import unittest
from testformats.struct_alignment8 import StructAlignment8

class TestStructAlignment8(unittest.TestCase):
    def test_struct_alignment8(self):
        with StructAlignment8.from_file('src/STRUCT_ALIGNMENT8.bin') as r:
            self.assertEqual(r.v.a_ulint.v, 1)
            self.assertEqual(r.v.a_lint.v, -2)
            self.assertEqual(r.v.udints.v[0], 3)
            self.assertEqual(r.v.udints.v[1], 4)
            self.assertEqual(r.v.a_alignment2_struct.a_bool.v, True)
            self.assertEqual(r.v.a_alignment2_struct.a_int.v, -1)
            self.assertEqual(r.v.a_alignment2_struct.a_uint.v, 2)
            self.assertEqual(r.v.a_alignment2_struct.bools.v[0], True)
            self.assertEqual(r.v.a_alignment2_struct.bools.v[1], False)
            self.assertEqual(r.v.a_alignment2_struct.bools.v[2], False)
            self.assertEqual(r.v.a_alignment2_struct.bools.v[3], True)
