# Autogenerated from KST: please remove this line if doing any edits by hand!

import unittest
from testformats.struct_small_arr_d2_e1_lh import StructSmallArrD2E1Lh

class TestStructSmallArrD2E1Lh(unittest.TestCase):
    def test_struct_small_arr_d2_e1_lh(self):
        with StructSmallArrD2E1Lh.from_file('src/STRUCT_SMALL_ARR_D2_E1_LH.bin') as r:
            self.assertEqual(r.v.v[0].v[0].s.v, u"a")
            self.assertEqual(r.v.v[0].v[0].u.v, 1)
