# Autogenerated from KST: please remove this line if doing any edits by hand!

import unittest
from testformats.struct_padded_lh import StructPaddedLh

class TestStructPaddedLh(unittest.TestCase):
    def test_struct_padded_lh(self):
        with StructPaddedLh.from_file('src/STRUCT_PADDED_LH.bin') as r:
            self.assertEqual(r.v.a_usint.v, 1)
            self.assertEqual(r.v.a_uint.v, 2)
            self.assertEqual(r.v.a_sint.v, -3)
            self.assertEqual(r.v.a_dint.v, -4)
            self.assertEqual(r.v.a_ulint.v, 5)
            self.assertEqual(r.v.a_bool.v, True)
