# Autogenerated from KST: please remove this line if doing any edits by hand!

import unittest
from testformats.struct_alignment4 import StructAlignment4

class TestStructAlignment4(unittest.TestCase):
    def test_struct_alignment4(self):
        with StructAlignment4.from_file('src/STRUCT_ALIGNMENT4.bin') as r:
            self.assertEqual(r.v.a_udint.v, 1)
            self.assertEqual(r.v.a_dint.v, -2)
            self.assertEqual(r.v.uints.v[0], 3)
            self.assertEqual(r.v.uints.v[1], 4)
            self.assertEqual(r.v.bytes.v[0], 5)
            self.assertEqual(r.v.bytes.v[1], 6)
            self.assertEqual(r.v.bytes.v[2], 7)
            self.assertEqual(r.v.bytes.v[3], 8)
