# Autogenerated from KST: please remove this line if doing any edits by hand!

import unittest
from testformats.struct_small_arr_d2_lh import StructSmallArrD2Lh

class TestStructSmallArrD2Lh(unittest.TestCase):
    def test_struct_small_arr_d2_lh(self):
        with StructSmallArrD2Lh.from_file('src/STRUCT_SMALL_ARR_D2_LH.bin') as r:
            self.assertEqual(r.v.v[0].v[0].s.v, u"a")
            self.assertEqual(r.v.v[0].v[0].u.v, 1)
            self.assertEqual(r.v.v[0].v[1].s.v, u"b")
            self.assertEqual(r.v.v[0].v[1].u.v, 2)
            self.assertEqual(r.v.v[0].v[2].s.v, u"c")
            self.assertEqual(r.v.v[0].v[2].u.v, 3)
            self.assertEqual(r.v.v[1].v[0].s.v, u"d")
            self.assertEqual(r.v.v[1].v[0].u.v, 4)
            self.assertEqual(r.v.v[1].v[1].s.v, u"e")
            self.assertEqual(r.v.v[1].v[1].u.v, 5)
            self.assertEqual(r.v.v[1].v[2].s.v, u"f")
            self.assertEqual(r.v.v[1].v[2].u.v, 6)
            self.assertEqual(r.v.v[2].v[0].s.v, u"g")
            self.assertEqual(r.v.v[2].v[0].u.v, 7)
            self.assertEqual(r.v.v[2].v[1].s.v, u"h")
            self.assertEqual(r.v.v[2].v[1].u.v, 8)
            self.assertEqual(r.v.v[2].v[2].s.v, u"i")
            self.assertEqual(r.v.v[2].v[2].u.v, 9)
