# Autogenerated from KST: please remove this line if doing any edits by hand!

import unittest
from testformats.struct_alignment1_arr_d1 import StructAlignment1ArrD1

class TestStructAlignment1ArrD1(unittest.TestCase):
    def test_struct_alignment1_arr_d1(self):
        with StructAlignment1ArrD1.from_file('src/STRUCT_ALIGNMENT1_ARR_D1.bin') as r:
            self.assertEqual(r.v.v[0].a_usint.v, 2)
            self.assertEqual(r.v.v[0].a_sint.v, -1)
            self.assertEqual(r.v.v[0].bytes.v[0], 3)
            self.assertEqual(r.v.v[0].bytes.v[1], 4)
            self.assertEqual(r.v.v[1].a_usint.v, 0)
            self.assertEqual(r.v.v[1].a_sint.v, 0)
            self.assertEqual(r.v.v[1].bytes.v[0], 0)
            self.assertEqual(r.v.v[1].bytes.v[1], 0)
            self.assertEqual(r.v.v[2].a_usint.v, 2)
            self.assertEqual(r.v.v[2].a_sint.v, -1)
            self.assertEqual(r.v.v[2].bytes.v[0], 3)
            self.assertEqual(r.v.v[2].bytes.v[1], 4)
