# Autogenerated from KST: please remove this line if doing any edits by hand!

import unittest
from testformats.struct_complex_lh import StructComplexLh

class TestStructComplexLh(unittest.TestCase):
    def test_struct_complex_lh(self):
        with StructComplexLh.from_file('src/STRUCT_COMPLEX_LH.bin') as r:
            self.assertEqual(r.v.a_usint.v, 128)
            self.assertEqual(r.v.alignment2_structs.v[0].a_bool.v, True)
            self.assertEqual(r.v.alignment2_structs.v[0].a_int.v, 1)
            self.assertEqual(r.v.alignment2_structs.v[0].a_uint.v, 2)
            self.assertEqual(r.v.alignment2_structs.v[0].bools.v[0], True)
            self.assertEqual(r.v.alignment2_structs.v[0].bools.v[1], False)
            self.assertEqual(r.v.alignment2_structs.v[0].bools.v[2], True)
            self.assertEqual(r.v.alignment2_structs.v[0].bools.v[3], False)
            self.assertEqual(r.v.alignment2_structs.v[1].a_bool.v, False)
            self.assertEqual(r.v.alignment2_structs.v[1].a_int.v, 3)
            self.assertEqual(r.v.alignment2_structs.v[1].a_uint.v, 4)
            self.assertEqual(r.v.alignment2_structs.v[1].bools.v[0], False)
            self.assertEqual(r.v.alignment2_structs.v[1].bools.v[1], True)
            self.assertEqual(r.v.alignment2_structs.v[1].bools.v[2], False)
            self.assertEqual(r.v.alignment2_structs.v[1].bools.v[3], True)
            self.assertEqual(r.v.a_alignment4_union.bytes.v[0], 5)
            self.assertEqual(r.v.a_alignment4_union.bytes.v[1], 0)
            self.assertEqual(r.v.a_alignment4_union.bytes.v[2], 0)
            self.assertEqual(r.v.a_alignment4_union.bytes.v[3], 0)
            self.assertEqual(r.v.a_alignment4_union.dwords.v[0], 5)
            self.assertEqual(r.v.a_alignment4_union.dwords.v[1], 6)
            self.assertEqual(r.v.a_bool.v, True)
            self.assertEqual(r.v.lints.v[0], -7)
            self.assertEqual(r.v.lints.v[1], 8)
            self.assertEqual(r.v.a_enum.v, 1)
