# Autogenerated from KST: please remove this line if doing any edits by hand!

import unittest
from testformats.union_struct_arr_d3_e1_lh import UnionStructArrD3E1Lh

class TestUnionStructArrD3E1Lh(unittest.TestCase):
    def test_union_struct_arr_d3_e1_lh(self):
        with UnionStructArrD3E1Lh.from_file('src/STRUCT_UNION_ARR_D3_E1_LH.bin') as r:
            self.assertEqual(r.v.v[0].v[0].v[0].alignment1_unions.v[0].bytes.v[0], 1)
            self.assertEqual(r.v.v[0].v[0].v[0].alignment1_unions.v[0].bytes.v[1], 2)
            self.assertEqual(r.v.v[0].v[0].v[0].alignment1_unions.v[0].bytes.v[2], 3)
            self.assertEqual(r.v.v[0].v[0].v[0].alignment1_unions.v[0].bytes.v[3], 4)
            self.assertEqual(r.v.v[0].v[0].v[0].alignment1_unions.v[1].bytes.v[0], 5)
            self.assertEqual(r.v.v[0].v[0].v[0].alignment1_unions.v[1].bytes.v[1], 6)
            self.assertEqual(r.v.v[0].v[0].v[0].alignment1_unions.v[1].bytes.v[2], 7)
            self.assertEqual(r.v.v[0].v[0].v[0].alignment1_unions.v[1].bytes.v[3], 8)
            self.assertEqual(r.v.v[0].v[0].v[0].alignment2_unions.v[0].a_bool.v, True)
            self.assertEqual(r.v.v[0].v[0].v[0].alignment2_unions.v[0].words.v[0], 9)
            self.assertEqual(r.v.v[0].v[0].v[0].alignment2_unions.v[0].words.v[1], 10)
            self.assertEqual(r.v.v[0].v[0].v[0].alignment2_unions.v[1].a_bool.v, True)
            self.assertEqual(r.v.v[0].v[0].v[0].alignment2_unions.v[1].words.v[0], 11)
            self.assertEqual(r.v.v[0].v[0].v[0].alignment2_unions.v[1].words.v[1], 12)
            self.assertEqual(r.v.v[0].v[0].v[0].a_alignment4_union.bytes.v[0], 13)
            self.assertEqual(r.v.v[0].v[0].v[0].a_alignment4_union.bytes.v[1], 0)
            self.assertEqual(r.v.v[0].v[0].v[0].a_alignment4_union.bytes.v[2], 0)
            self.assertEqual(r.v.v[0].v[0].v[0].a_alignment4_union.bytes.v[3], 0)
            self.assertEqual(r.v.v[0].v[0].v[0].a_alignment4_union.dwords.v[0], 13)
            self.assertEqual(r.v.v[0].v[0].v[0].a_alignment4_union.dwords.v[1], 14)
            self.assertEqual(r.v.v[0].v[0].v[0].a_alignment8_union.words.v[0], 15)
            self.assertEqual(r.v.v[0].v[0].v[0].a_alignment8_union.words.v[1], 0)
            self.assertEqual(r.v.v[0].v[0].v[0].a_alignment8_union.words.v[2], 0)
            self.assertEqual(r.v.v[0].v[0].v[0].a_alignment8_union.words.v[3], 0)
            self.assertEqual(r.v.v[0].v[0].v[0].a_alignment8_union.a_lword.v, 15)
