# Autogenerated from KST: please remove this line if doing any edits by hand!

import unittest
from testformats.struct_nest3_lh import StructNest3Lh

class TestStructNest3Lh(unittest.TestCase):
    def test_struct_nest3_lh(self):
        with StructNest3Lh.from_file('src/STRUCT_NEST3_LH.bin') as r:
            self.assertEqual(r.v.a_small_struct.u.v, 5)
            self.assertEqual(r.v.a_small_struct.s.v, u"L3")
            self.assertEqual(r.v.a_nest2_struct.a_small_struct.u.v, 3)
            self.assertEqual(r.v.a_nest2_struct.a_small_struct.s.v, u"L2")
            self.assertEqual(r.v.a_nest2_struct.a_nest1_struct.a_small_struct.u.v, 1)
            self.assertEqual(r.v.a_nest2_struct.a_nest1_struct.a_small_struct.s.v, u"L1")
            self.assertEqual(r.v.a_nest2_struct.a_nest1_struct.a_int.v, -2)
            self.assertEqual(r.v.a_nest2_struct.a_dint.v, -4)
            self.assertEqual(r.v.a_lint.v, -6)
