# Autogenerated from KST: please remove this line if doing any edits by hand!

import unittest
from specwrite.common_spec import CommonSpec

from testwrite.lword_arr_d1_lh import LwordArrD1Lh

class TestLwordArrD1Lh(CommonSpec.Base):
    def __init__(self, *args, **kwargs):
        super(TestLwordArrD1Lh, self).__init__(*args, **kwargs)
        self.struct_class = LwordArrD1Lh
        self.src_filename = 'src/LWORD_ARR_D1_LH.bin'
