# Autogenerated from KST: please remove this line if doing any edits by hand!

import unittest
from specwrite.common_spec import CommonSpec

from testwrite.lint_arr_d3_lh import LintArrD3Lh

class TestLintArrD3Lh(CommonSpec.Base):
    def __init__(self, *args, **kwargs):
        super(TestLintArrD3Lh, self).__init__(*args, **kwargs)
        self.struct_class = LintArrD3Lh
        self.src_filename = 'src/LINT_ARR_D3_LH.bin'
