# Autogenerated from KST: please remove this line if doing any edits by hand!

import unittest
from specwrite.common_spec import CommonSpec

from testwrite.real_arr_d1_e1_lh import RealArrD1E1Lh

class TestRealArrD1E1Lh(CommonSpec.Base):
    def __init__(self, *args, **kwargs):
        super(TestRealArrD1E1Lh, self).__init__(*args, **kwargs)
        self.struct_class = RealArrD1E1Lh
        self.src_filename = 'src/REAL_ARR_D1_E1_LH.bin'
