# Autogenerated from KST: please remove this line if doing any edits by hand!

import unittest
from specwrite.common_spec import CommonSpec

from testwrite.uint_arr_d3_lh import UintArrD3Lh

class TestUintArrD3Lh(CommonSpec.Base):
    def __init__(self, *args, **kwargs):
        super(TestUintArrD3Lh, self).__init__(*args, **kwargs)
        self.struct_class = UintArrD3Lh
        self.src_filename = 'src/UINT_ARR_D3_E1_LH.bin'
