# Autogenerated from KST: please remove this line if doing any edits by hand!

import unittest
from specwrite.common_spec import CommonSpec

from testwrite.real_arr_d1_lh import RealArrD1Lh

class TestRealArrD1Lh(CommonSpec.Base):
    def __init__(self, *args, **kwargs):
        super(TestRealArrD1Lh, self).__init__(*args, **kwargs)
        self.struct_class = RealArrD1Lh
        self.src_filename = 'src/REAL_ARR_D1_LH.bin'
