# Autogenerated from KST: please remove this line if doing any edits by hand!

import unittest
from specwrite.common_spec import CommonSpec

from testwrite.sint_arr_d1_lh import SintArrD1Lh

class TestSintArrD1Lh(CommonSpec.Base):
    def __init__(self, *args, **kwargs):
        super(TestSintArrD1Lh, self).__init__(*args, **kwargs)
        self.struct_class = SintArrD1Lh
        self.src_filename = 'src/SINT_ARR_D1_LH.bin'
