# Autogenerated from KST: please remove this line if doing any edits by hand!

import unittest
from specwrite.common_spec import CommonSpec

from testwrite.dword_arr_d2_lh import DwordArrD2Lh

class TestDwordArrD2Lh(CommonSpec.Base):
    def __init__(self, *args, **kwargs):
        super(TestDwordArrD2Lh, self).__init__(*args, **kwargs)
        self.struct_class = DwordArrD2Lh
        self.src_filename = 'src/DWORD_ARR_D2_LH.bin'
