# Autogenerated from KST: please remove this line if doing any edits by hand!

import unittest
from specwrite.common_spec import CommonSpec

from testwrite.time_of_day_arr_d3_lh import TimeOfDayArrD3Lh

class TestTimeOfDayArrD3Lh(CommonSpec.Base):
    def __init__(self, *args, **kwargs):
        super(TestTimeOfDayArrD3Lh, self).__init__(*args, **kwargs)
        self.struct_class = TimeOfDayArrD3Lh
        self.src_filename = 'src/TOD_ARR_D3_LH.bin'
