# Autogenerated from KST: please remove this line if doing any edits by hand!

import unittest
from specwrite.common_spec import CommonSpec

from testwrite.dint_arr_d3_lh import DintArrD3Lh

class TestDintArrD3Lh(CommonSpec.Base):
    def __init__(self, *args, **kwargs):
        super(TestDintArrD3Lh, self).__init__(*args, **kwargs)
        self.struct_class = DintArrD3Lh
        self.src_filename = 'src/DINT_ARR_D3_LH.bin'
