# Autogenerated from KST: please remove this line if doing any edits by hand!

import unittest
from specwrite.common_spec import CommonSpec

from testwrite.align import Align

class TestAlign(CommonSpec.Base):
    def __init__(self, *args, **kwargs):
        super(TestAlign, self).__init__(*args, **kwargs)
        self.struct_class = Align
        self.src_filename = 'src/LWORD_ARR_D3_LH.bin'
