# Autogenerated from KST: please remove this line if doing any edits by hand!

import unittest
from specwrite.common_spec import CommonSpec

from testwrite.ulint_arr_d1_lh import UlintArrD1Lh

class TestUlintArrD1Lh(CommonSpec.Base):
    def __init__(self, *args, **kwargs):
        super(TestUlintArrD1Lh, self).__init__(*args, **kwargs)
        self.struct_class = UlintArrD1Lh
        self.src_filename = 'src/ULINT_ARR_D1_LH.bin'
