# Autogenerated from KST: please remove this line if doing any edits by hand!

import unittest
from specwrite.common_spec import CommonSpec

from testwrite.string_3byte_char_by_toarybyte_lh import String3byteCharByToarybyteLh

class TestString3byteCharByToarybyteLh(CommonSpec.Base):
    def __init__(self, *args, **kwargs):
        super(TestString3byteCharByToarybyteLh, self).__init__(*args, **kwargs)
        self.struct_class = String3byteCharByToarybyteLh
        self.src_filename = 'src/STRING_3BYTE_CHAR_BY_TOARYBYTE_LH.bin'
