# Autogenerated from KST: please remove this line if doing any edits by hand!

import unittest
from specwrite.common_spec import CommonSpec

from testwrite.lword_arr_d3_lh import LwordArrD3Lh

class TestLwordArrD3Lh(CommonSpec.Base):
    def __init__(self, *args, **kwargs):
        super(TestLwordArrD3Lh, self).__init__(*args, **kwargs)
        self.struct_class = LwordArrD3Lh
        self.src_filename = 'src/LWORD_ARR_D3_LH.bin'
