# Autogenerated from KST: please remove this line if doing any edits by hand!

import unittest
from specwrite.common_spec import CommonSpec

from testwrite.udint_arr_d2_lh import UdintArrD2Lh

class TestUdintArrD2Lh(CommonSpec.Base):
    def __init__(self, *args, **kwargs):
        super(TestUdintArrD2Lh, self).__init__(*args, **kwargs)
        self.struct_class = UdintArrD2Lh
        self.src_filename = 'src/UDINT_ARR_D2_LH.bin'
