# Autogenerated from KST: please remove this line if doing any edits by hand!

import unittest
from specwrite.common_spec import CommonSpec

from testwrite.sint_arr_d1_e1_lh import SintArrD1E1Lh

class TestSintArrD1E1Lh(CommonSpec.Base):
    def __init__(self, *args, **kwargs):
        super(TestSintArrD1E1Lh, self).__init__(*args, **kwargs)
        self.struct_class = SintArrD1E1Lh
        self.src_filename = 'src/SINT_ARR_D1_E1_LH.bin'
