# Autogenerated from KST: please remove this line if doing any edits by hand!

import unittest
from specwrite.common_spec import CommonSpec

from testwrite.dword_arr_d1_lh import DwordArrD1Lh

class TestDwordArrD1Lh(CommonSpec.Base):
    def __init__(self, *args, **kwargs):
        super(TestDwordArrD1Lh, self).__init__(*args, **kwargs)
        self.struct_class = DwordArrD1Lh
        self.src_filename = 'src/DWORD_ARR_D1_LH.bin'
