# Autogenerated from KST: please remove this line if doing any edits by hand!

import unittest
from specwrite.common_spec import CommonSpec

from testwrite.time_of_day_arr_d1_e1_lh import TimeOfDayArrD1E1Lh

class TestTimeOfDayArrD1E1Lh(CommonSpec.Base):
    def __init__(self, *args, **kwargs):
        super(TestTimeOfDayArrD1E1Lh, self).__init__(*args, **kwargs)
        self.struct_class = TimeOfDayArrD1E1Lh
        self.src_filename = 'src/TOD_ARR_D1_E1_LH.bin'
