# Autogenerated from KST: please remove this line if doing any edits by hand!

import unittest
from specwrite.common_spec import CommonSpec

from testwrite.dint_arr_d2_lh import DintArrD2Lh

class TestDintArrD2Lh(CommonSpec.Base):
    def __init__(self, *args, **kwargs):
        super(TestDintArrD2Lh, self).__init__(*args, **kwargs)
        self.struct_class = DintArrD2Lh
        self.src_filename = 'src/DINT_ARR_D2_LH.bin'
