# Autogenerated from KST: please remove this line if doing any edits by hand!

import unittest
from specwrite.common_spec import CommonSpec

from testwrite.lint_arr_d1_lh import LintArrD1Lh

class TestLintArrD1Lh(CommonSpec.Base):
    def __init__(self, *args, **kwargs):
        super(TestLintArrD1Lh, self).__init__(*args, **kwargs)
        self.struct_class = LintArrD1Lh
        self.src_filename = 'src/LINT_ARR_D1_LH.bin'
