# Autogenerated from KST: please remove this line if doing any edits by hand!

import unittest
from specwrite.common_spec import CommonSpec

from testwrite.word_arr_d3_lh import WordArrD3Lh

class TestWordArrD3Lh(CommonSpec.Base):
    def __init__(self, *args, **kwargs):
        super(TestWordArrD3Lh, self).__init__(*args, **kwargs)
        self.struct_class = WordArrD3Lh
        self.src_filename = 'src/WORD_ARR_D3_LH.bin'
