# Autogenerated from KST: please remove this line if doing any edits by hand!

import unittest
from specwrite.common_spec import CommonSpec

from testwrite.word_arr_d2_e1_lh import WordArrD2E1Lh

class TestWordArrD2E1Lh(CommonSpec.Base):
    def __init__(self, *args, **kwargs):
        super(TestWordArrD2E1Lh, self).__init__(*args, **kwargs)
        self.struct_class = WordArrD2E1Lh
        self.src_filename = 'src/WORD_ARR_D2_E1_LH.bin'
