# Autogenerated from KST: please remove this line if doing any edits by hand!

import unittest
from specwrite.common_spec import CommonSpec

from testwrite.date_and_time_arr_d2_e1_lh import DateAndTimeArrD2E1Lh

class TestDateAndTimeArrD2E1Lh(CommonSpec.Base):
    def __init__(self, *args, **kwargs):
        super(TestDateAndTimeArrD2E1Lh, self).__init__(*args, **kwargs)
        self.struct_class = DateAndTimeArrD2E1Lh
        self.src_filename = 'src/DT_ARR_D2_E1_LH.bin'
