# Autogenerated from KST: please remove this line if doing any edits by hand!

import unittest
from specwrite.common_spec import CommonSpec

from testwrite.date_arr_d2_lh import DateArrD2Lh

class TestDateArrD2Lh(CommonSpec.Base):
    def __init__(self, *args, **kwargs):
        super(TestDateArrD2Lh, self).__init__(*args, **kwargs)
        self.struct_class = DateArrD2Lh
        self.src_filename = 'src/DATE_ARR_D2_LH.bin'
