# Autogenerated from KST: please remove this line if doing any edits by hand!

import unittest
from specwrite.common_spec import CommonSpec

from testwrite.lreal_arr_d1_lh import LrealArrD1Lh

class TestLrealArrD1Lh(CommonSpec.Base):
    def __init__(self, *args, **kwargs):
        super(TestLrealArrD1Lh, self).__init__(*args, **kwargs)
        self.struct_class = LrealArrD1Lh
        self.src_filename = 'src/LREAL_ARR_D1_LH.bin'
