# Autogenerated from KST: please remove this line if doing any edits by hand!

import unittest
from specwrite.common_spec import CommonSpec

from testwrite.string_n2_by_toarybyte_lh import StringN2ByToarybyteLh

class TestStringN2ByToarybyteLh(CommonSpec.Base):
    def __init__(self, *args, **kwargs):
        super(TestStringN2ByToarybyteLh, self).__init__(*args, **kwargs)
        self.struct_class = StringN2ByToarybyteLh
        self.src_filename = 'src/STRING_N2_BY_TOARYBYTE_LH.bin'
