# Autogenerated from KST: please remove this line if doing any edits by hand!

import unittest
from specwrite.common_spec import CommonSpec

from testwrite.dint_arr_d3_e1_lh import DintArrD3E1Lh

class TestDintArrD3E1Lh(CommonSpec.Base):
    def __init__(self, *args, **kwargs):
        super(TestDintArrD3E1Lh, self).__init__(*args, **kwargs)
        self.struct_class = DintArrD3E1Lh
        self.src_filename = 'src/DINT_ARR_D3_E1_LH.bin'
