# Autogenerated from KST: please remove this line if doing any edits by hand!

import unittest
from specwrite.common_spec import CommonSpec

from testwrite.date_and_time_arr_d1_lh import DateAndTimeArrD1Lh

class TestDateAndTimeArrD1Lh(CommonSpec.Base):
    def __init__(self, *args, **kwargs):
        super(TestDateAndTimeArrD1Lh, self).__init__(*args, **kwargs)
        self.struct_class = DateAndTimeArrD1Lh
        self.src_filename = 'src/DT_ARR_D1_LH.bin'
