# Autogenerated from KST: please remove this line if doing any edits by hand!

import unittest
from specwrite.common_spec import CommonSpec

from testwrite.lword_arr_d2_lh import LwordArrD2Lh

class TestLwordArrD2Lh(CommonSpec.Base):
    def __init__(self, *args, **kwargs):
        super(TestLwordArrD2Lh, self).__init__(*args, **kwargs)
        self.struct_class = LwordArrD2Lh
        self.src_filename = 'src/LWORD_ARR_D2_LH.bin'
