# Autogenerated from KST: please remove this line if doing any edits by hand!

import unittest
from specwrite.common_spec import CommonSpec

from testwrite.byte_arr_d3_lh import ByteArrD3Lh

class TestByteArrD3Lh(CommonSpec.Base):
    def __init__(self, *args, **kwargs):
        super(TestByteArrD3Lh, self).__init__(*args, **kwargs)
        self.struct_class = ByteArrD3Lh
        self.src_filename = 'src/BYTE_ARR_D3_LH.bin'
