# Autogenerated from KST: please remove this line if doing any edits by hand!

import unittest
from specwrite.common_spec import CommonSpec

from testwrite.date_arr_d3_lh import DateArrD3Lh

class TestDateArrD3Lh(CommonSpec.Base):
    def __init__(self, *args, **kwargs):
        super(TestDateArrD3Lh, self).__init__(*args, **kwargs)
        self.struct_class = DateArrD3Lh
        self.src_filename = 'src/DATE_ARR_D3_LH.bin'
