# Autogenerated from KST: please remove this line if doing any edits by hand!

import unittest
from specwrite.common_spec import CommonSpec

from testwrite.byte_arr_d1_lh import ByteArrD1Lh

class TestByteArrD1Lh(CommonSpec.Base):
    def __init__(self, *args, **kwargs):
        super(TestByteArrD1Lh, self).__init__(*args, **kwargs)
        self.struct_class = ByteArrD1Lh
        self.src_filename = 'src/BYTE_ARR_D1_LH.bin'
