# Autogenerated from KST: please remove this line if doing any edits by hand!

import unittest
from specwrite.common_spec import CommonSpec

from testwrite.udint_arr_d3_lh import UdintArrD3Lh

class TestUdintArrD3Lh(CommonSpec.Base):
    def __init__(self, *args, **kwargs):
        super(TestUdintArrD3Lh, self).__init__(*args, **kwargs)
        self.struct_class = UdintArrD3Lh
        self.src_filename = 'src/UDINT_ARR_D3_LH.bin'
