# Autogenerated from KST: please remove this line if doing any edits by hand!

import unittest
from specwrite.common_spec import CommonSpec

from testwrite.dword_arr_d3_lh import DwordArrD3Lh

class TestDwordArrD3Lh(CommonSpec.Base):
    def __init__(self, *args, **kwargs):
        super(TestDwordArrD3Lh, self).__init__(*args, **kwargs)
        self.struct_class = DwordArrD3Lh
        self.src_filename = 'src/DWORD_ARR_D3_LH.bin'
