# Autogenerated from KST: please remove this line if doing any edits by hand!

import unittest
from specwrite.common_spec import CommonSpec

from testwrite.word_arr_d1_lh import WordArrD1Lh

class TestWordArrD1Lh(CommonSpec.Base):
    def __init__(self, *args, **kwargs):
        super(TestWordArrD1Lh, self).__init__(*args, **kwargs)
        self.struct_class = WordArrD1Lh
        self.src_filename = 'src/WORD_ARR_D1_LH.bin'
