# Autogenerated from KST: please remove this line if doing any edits by hand!

import unittest
from specwrite.common_spec import CommonSpec

from testwrite.date_arr_d3_e1_lh import DateArrD3E1Lh

class TestDateArrD3E1Lh(CommonSpec.Base):
    def __init__(self, *args, **kwargs):
        super(TestDateArrD3E1Lh, self).__init__(*args, **kwargs)
        self.struct_class = DateArrD3E1Lh
        self.src_filename = 'src/DATE_ARR_D3_E1_LH.bin'
