# Autogenerated from KST: please remove this line if doing any edits by hand!

import unittest
from specwrite.common_spec import CommonSpec

from testwrite.uint_arr_d2_lh import UintArrD2Lh

class TestUintArrD2Lh(CommonSpec.Base):
    def __init__(self, *args, **kwargs):
        super(TestUintArrD2Lh, self).__init__(*args, **kwargs)
        self.struct_class = UintArrD2Lh
        self.src_filename = 'src/UINT_ARR_D2_LH.bin'
