# Autogenerated from KST: please remove this line if doing any edits by hand!

import unittest
from specwrite.common_spec import CommonSpec

from testwrite.date_and_time_arr_d2_lh import DateAndTimeArrD2Lh

class TestDateAndTimeArrD2Lh(CommonSpec.Base):
    def __init__(self, *args, **kwargs):
        super(TestDateAndTimeArrD2Lh, self).__init__(*args, **kwargs)
        self.struct_class = DateAndTimeArrD2Lh
        self.src_filename = 'src/DT_ARR_D2_LH.bin'
