# Autogenerated from KST: please remove this line if doing any edits by hand!

import unittest
from specwrite.common_spec import CommonSpec

from testwrite.sint_arr_d3_e1_lh import SintArrD3E1Lh

class TestSintArrD3E1Lh(CommonSpec.Base):
    def __init__(self, *args, **kwargs):
        super(TestSintArrD3E1Lh, self).__init__(*args, **kwargs)
        self.struct_class = SintArrD3E1Lh
        self.src_filename = 'src/SINT_ARR_D3_E1_LH.bin'
