# Autogenerated from KST: please remove this line if doing any edits by hand!

import unittest
from specwrite.common_spec import CommonSpec

from testwrite.word_arr_d1_e1_lh import WordArrD1E1Lh

class TestWordArrD1E1Lh(CommonSpec.Base):
    def __init__(self, *args, **kwargs):
        super(TestWordArrD1E1Lh, self).__init__(*args, **kwargs)
        self.struct_class = WordArrD1E1Lh
        self.src_filename = 'src/WORD_ARR_D1_E1_LH.bin'
