# Autogenerated from KST: please remove this line if doing any edits by hand!

import unittest
from specwrite.common_spec import CommonSpec

from testwrite.lreal_arr_d2_lh import LrealArrD2Lh

class TestLrealArrD2Lh(CommonSpec.Base):
    def __init__(self, *args, **kwargs):
        super(TestLrealArrD2Lh, self).__init__(*args, **kwargs)
        self.struct_class = LrealArrD2Lh
        self.src_filename = 'src/LREAL_ARR_D2_LH.bin'
