# Autogenerated from KST: please remove this line if doing any edits by hand!

import unittest
from specwrite.common_spec import CommonSpec

from testwrite.lreal_arr_d3_lh import LrealArrD3Lh

class TestLrealArrD3Lh(CommonSpec.Base):
    def __init__(self, *args, **kwargs):
        super(TestLrealArrD3Lh, self).__init__(*args, **kwargs)
        self.struct_class = LrealArrD3Lh
        self.src_filename = 'src/LREAL_ARR_D3_LH.bin'
