# Autogenerated from KST: please remove this line if doing any edits by hand!

import unittest
from specwrite.common_spec import CommonSpec

from testwrite.int_arr_d2_e1_lh import IntArrD2E1Lh

class TestIntArrD2E1Lh(CommonSpec.Base):
    def __init__(self, *args, **kwargs):
        super(TestIntArrD2E1Lh, self).__init__(*args, **kwargs)
        self.struct_class = IntArrD2E1Lh
        self.src_filename = 'src/INT_ARR_D2_E1_LH.bin'
