# Autogenerated from KST: please remove this line if doing any edits by hand!

import unittest
from specwrite.common_spec import CommonSpec

from testwrite.byte_arr_d2_lh import ByteArrD2Lh

class TestByteArrD2Lh(CommonSpec.Base):
    def __init__(self, *args, **kwargs):
        super(TestByteArrD2Lh, self).__init__(*args, **kwargs)
        self.struct_class = ByteArrD2Lh
        self.src_filename = 'src/BYTE_ARR_D2_LH.bin'
