# Autogenerated from KST: please remove this line if doing any edits by hand!

import unittest
from specwrite.common_spec import CommonSpec

from testwrite.dint_arr_d1_lh import DintArrD1Lh

class TestDintArrD1Lh(CommonSpec.Base):
    def __init__(self, *args, **kwargs):
        super(TestDintArrD1Lh, self).__init__(*args, **kwargs)
        self.struct_class = DintArrD1Lh
        self.src_filename = 'src/DINT_ARR_D1_LH.bin'
