# Autogenerated from KST: please remove this line if doing any edits by hand!

import unittest
from specwrite.common_spec import CommonSpec

from testwrite.string_4byte_char_by_toarybyte_lh import String4byteCharByToarybyteLh

class TestString4byteCharByToarybyteLh(CommonSpec.Base):
    def __init__(self, *args, **kwargs):
        super(TestString4byteCharByToarybyteLh, self).__init__(*args, **kwargs)
        self.struct_class = String4byteCharByToarybyteLh
        self.src_filename = 'src/STRING_4BYTE_CHAR_BY_TOARYBYTE_LH.bin'
