# Autogenerated from KST: please remove this line if doing any edits by hand!

import unittest
from specwrite.common_spec import CommonSpec

from testwrite.uint_arr_d1_lh import UintArrD1Lh

class TestUintArrD1Lh(CommonSpec.Base):
    def __init__(self, *args, **kwargs):
        super(TestUintArrD1Lh, self).__init__(*args, **kwargs)
        self.struct_class = UintArrD1Lh
        self.src_filename = 'src/UINT_ARR_D1_LH.bin'
