# Autogenerated from KST: please remove this line if doing any edits by hand!

import unittest
from specwrite.common_spec import CommonSpec

from testwrite.lword_arr_d2_e1_lh import LwordArrD2E1Lh

class TestLwordArrD2E1Lh(CommonSpec.Base):
    def __init__(self, *args, **kwargs):
        super(TestLwordArrD2E1Lh, self).__init__(*args, **kwargs)
        self.struct_class = LwordArrD2E1Lh
        self.src_filename = 'src/LWORD_ARR_D2_E1_LH.bin'
