# Autogenerated from KST: please remove this line if doing any edits by hand!

import unittest
from specwrite.common_spec import CommonSpec

from testwrite.int_arr_d3_e1_lh import IntArrD3E1Lh

class TestIntArrD3E1Lh(CommonSpec.Base):
    def __init__(self, *args, **kwargs):
        super(TestIntArrD3E1Lh, self).__init__(*args, **kwargs)
        self.struct_class = IntArrD3E1Lh
        self.src_filename = 'src/INT_ARR_D3_E1_LH.bin'
