# Autogenerated from KST: please remove this line if doing any edits by hand!

import unittest
from specwrite.common_spec import CommonSpec

from testwrite.int_arr_d1_lh import IntArrD1Lh

class TestIntArrD1Lh(CommonSpec.Base):
    def __init__(self, *args, **kwargs):
        super(TestIntArrD1Lh, self).__init__(*args, **kwargs)
        self.struct_class = IntArrD1Lh
        self.src_filename = 'src/INT_ARR_D1_LH.bin'
