# Autogenerated from KST: please remove this line if doing any edits by hand!

import unittest
from specwrite.common_spec import CommonSpec

from testwrite.string_2byte_char_by_toarybyte_lh import String2byteCharByToarybyteLh

class TestString2byteCharByToarybyteLh(CommonSpec.Base):
    def __init__(self, *args, **kwargs):
        super(TestString2byteCharByToarybyteLh, self).__init__(*args, **kwargs)
        self.struct_class = String2byteCharByToarybyteLh
        self.src_filename = 'src/STRING_2BYTE_CHAR_BY_TOARYBYTE_LH.bin'
