# Autogenerated from KST: please remove this line if doing any edits by hand!

import unittest
from specwrite.common_spec import CommonSpec

from testwrite.lint_arr_d3_e1_lh import LintArrD3E1Lh

class TestLintArrD3E1Lh(CommonSpec.Base):
    def __init__(self, *args, **kwargs):
        super(TestLintArrD3E1Lh, self).__init__(*args, **kwargs)
        self.struct_class = LintArrD3E1Lh
        self.src_filename = 'src/LINT_ARR_D3_E1_LH.bin'
