# Autogenerated from KST: please remove this line if doing any edits by hand!

import unittest
from specwrite.common_spec import CommonSpec

from testwrite.string_n16_by_toarybyte_lh import StringN16ByToarybyteLh

class TestStringN16ByToarybyteLh(CommonSpec.Base):
    def __init__(self, *args, **kwargs):
        super(TestStringN16ByToarybyteLh, self).__init__(*args, **kwargs)
        self.struct_class = StringN16ByToarybyteLh
        self.src_filename = 'src/STRING_N16_BY_TOARYBYTE_LH.bin'
