# Autogenerated from KST: please remove this line if doing any edits by hand!

import unittest
from specwrite.common_spec import CommonSpec

from testwrite.time_arr_d3_lh import TimeArrD3Lh

class TestTimeArrD3Lh(CommonSpec.Base):
    def __init__(self, *args, **kwargs):
        super(TestTimeArrD3Lh, self).__init__(*args, **kwargs)
        self.struct_class = TimeArrD3Lh
        self.src_filename = 'src/TIME_ARR_D3_LH.bin'
