# Autogenerated from KST: please remove this line if doing any edits by hand!

import unittest
from specwrite.common_spec import CommonSpec

from testwrite.time_of_day_arr_d2_lh import TimeOfDayArrD2Lh

class TestTimeOfDayArrD2Lh(CommonSpec.Base):
    def __init__(self, *args, **kwargs):
        super(TestTimeOfDayArrD2Lh, self).__init__(*args, **kwargs)
        self.struct_class = TimeOfDayArrD2Lh
        self.src_filename = 'src/TOD_ARR_D2_LH.bin'
