# Autogenerated from KST: please remove this line if doing any edits by hand!

import unittest
from specwrite.common_spec import CommonSpec

from testwrite.ulint_arr_d3_lh import UlintArrD3Lh

class TestUlintArrD3Lh(CommonSpec.Base):
    def __init__(self, *args, **kwargs):
        super(TestUlintArrD3Lh, self).__init__(*args, **kwargs)
        self.struct_class = UlintArrD3Lh
        self.src_filename = 'src/ULINT_ARR_D3_LH.bin'
