# Autogenerated from KST: please remove this line if doing any edits by hand!

import unittest
from specwrite.common_spec import CommonSpec

from testwrite.ulint_arr_d3_e1_lh import UlintArrD3E1Lh

class TestUlintArrD3E1Lh(CommonSpec.Base):
    def __init__(self, *args, **kwargs):
        super(TestUlintArrD3E1Lh, self).__init__(*args, **kwargs)
        self.struct_class = UlintArrD3E1Lh
        self.src_filename = 'src/ULINT_ARR_D3_E1_LH.bin'
