# Autogenerated from KST: please remove this line if doing any edits by hand!

import unittest
from specwrite.common_spec import CommonSpec

from testwrite.udint_arr_d1_lh import UdintArrD1Lh

class TestUdintArrD1Lh(CommonSpec.Base):
    def __init__(self, *args, **kwargs):
        super(TestUdintArrD1Lh, self).__init__(*args, **kwargs)
        self.struct_class = UdintArrD1Lh
        self.src_filename = 'src/UDINT_ARR_D1_LH.bin'
