# Autogenerated from KST: please remove this line if doing any edits by hand!

import unittest
from specwrite.common_spec import CommonSpec

from testwrite.sint_arr_d2_lh import SintArrD2Lh

class TestSintArrD2Lh(CommonSpec.Base):
    def __init__(self, *args, **kwargs):
        super(TestSintArrD2Lh, self).__init__(*args, **kwargs)
        self.struct_class = SintArrD2Lh
        self.src_filename = 'src/SINT_ARR_D2_LH.bin'
