# Autogenerated from KST: please remove this line if doing any edits by hand!

import unittest
from specwrite.common_spec import CommonSpec

from testwrite.dint_arr_d1_e1_lh import DintArrD1E1Lh

class TestDintArrD1E1Lh(CommonSpec.Base):
    def __init__(self, *args, **kwargs):
        super(TestDintArrD1E1Lh, self).__init__(*args, **kwargs)
        self.struct_class = DintArrD1E1Lh
        self.src_filename = 'src/DINT_ARR_D1_E1_LH.bin'
