# Autogenerated from KST: please remove this line if doing any edits by hand!

import unittest
from specwrite.common_spec import CommonSpec

from testwrite.date_arr_d1_lh import DateArrD1Lh

class TestDateArrD1Lh(CommonSpec.Base):
    def __init__(self, *args, **kwargs):
        super(TestDateArrD1Lh, self).__init__(*args, **kwargs)
        self.struct_class = DateArrD1Lh
        self.src_filename = 'src/DATE_ARR_D1_LH.bin'
