# Autogenerated from KST: please remove this line if doing any edits by hand!

import unittest
from specwrite.common_spec import CommonSpec

from testwrite.fixed_align import FixedAlign

class TestFixedAlign(CommonSpec.Base):
    def __init__(self, *args, **kwargs):
        super(TestFixedAlign, self).__init__(*args, **kwargs)
        self.struct_class = FixedAlign
        self.src_filename = 'src/LWORD_ARR_D3_LH.bin'
