# Autogenerated from KST: please remove this line if doing any edits by hand!

import unittest
from specwrite.common_spec import CommonSpec

from testwrite.int_arr_d3_lh import IntArrD3Lh

class TestIntArrD3Lh(CommonSpec.Base):
    def __init__(self, *args, **kwargs):
        super(TestIntArrD3Lh, self).__init__(*args, **kwargs)
        self.struct_class = IntArrD3Lh
        self.src_filename = 'src/INT_ARR_D3_LH.bin'
