# Autogenerated from KST: please remove this line if doing any edits by hand!

import unittest
from specwrite.common_spec import CommonSpec

from testwrite.word_arr_d2_lh import WordArrD2Lh

class TestWordArrD2Lh(CommonSpec.Base):
    def __init__(self, *args, **kwargs):
        super(TestWordArrD2Lh, self).__init__(*args, **kwargs)
        self.struct_class = WordArrD2Lh
        self.src_filename = 'src/WORD_ARR_D2_LH.bin'
