# Autogenerated from KST: please remove this line if doing any edits by hand!

import unittest
from specwrite.common_spec import CommonSpec

from testwrite.time_arr_d2_lh import TimeArrD2Lh

class TestTimeArrD2Lh(CommonSpec.Base):
    def __init__(self, *args, **kwargs):
        super(TestTimeArrD2Lh, self).__init__(*args, **kwargs)
        self.struct_class = TimeArrD2Lh
        self.src_filename = 'src/TIME_ARR_D2_LH.bin'
