# Autogenerated from KST: please remove this line if doing any edits by hand!

import unittest
from specwrite.common_spec import CommonSpec

from testwrite.bool_arr_d1_lh_flat import BoolArrD1LhFlat

class TestBoolArrD1LhFlat(CommonSpec.Base):
    def __init__(self, *args, **kwargs):
        super(TestBoolArrD1LhFlat, self).__init__(*args, **kwargs)
        self.struct_class = BoolArrD1LhFlat
        self.src_filename = 'src/BOOL_ARR_D1_LH.bin'
