# Autogenerated from KST: please remove this line if doing any edits by hand!

import unittest
from specwrite.common_spec import CommonSpec

from testwrite.real_arr_d2_lh import RealArrD2Lh

class TestRealArrD2Lh(CommonSpec.Base):
    def __init__(self, *args, **kwargs):
        super(TestRealArrD2Lh, self).__init__(*args, **kwargs)
        self.struct_class = RealArrD2Lh
        self.src_filename = 'src/REAL_ARR_D2_LH.bin'
