# Autogenerated from KST: please remove this line if doing any edits by hand!

import unittest
from specwrite.common_spec import CommonSpec

from testwrite.bool_arr_d2_lh import BoolArrD2Lh

class TestBoolArrD2Lh(CommonSpec.Base):
    def __init__(self, *args, **kwargs):
        super(TestBoolArrD2Lh, self).__init__(*args, **kwargs)
        self.struct_class = BoolArrD2Lh
        self.src_filename = 'src/BOOL_ARR_D2_LH.bin'
