# Autogenerated from KST: please remove this line if doing any edits by hand!

import unittest
from specwrite.common_spec import CommonSpec

from testwrite.usint_arr_d2_lh import UsintArrD2Lh

class TestUsintArrD2Lh(CommonSpec.Base):
    def __init__(self, *args, **kwargs):
        super(TestUsintArrD2Lh, self).__init__(*args, **kwargs)
        self.struct_class = UsintArrD2Lh
        self.src_filename = 'src/USINT_ARR_D2_LH.bin'
