# Autogenerated from KST: please remove this line if doing any edits by hand!

import unittest
from specwrite.common_spec import CommonSpec

from testwrite.time_of_day_arr_d3_e1_lh import TimeOfDayArrD3E1Lh

class TestTimeOfDayArrD3E1Lh(CommonSpec.Base):
    def __init__(self, *args, **kwargs):
        super(TestTimeOfDayArrD3E1Lh, self).__init__(*args, **kwargs)
        self.struct_class = TimeOfDayArrD3E1Lh
        self.src_filename = 'src/TOD_ARR_D3_E1_LH.bin'
