# Autogenerated from KST: please remove this line if doing any edits by hand!

import unittest
from specwrite.common_spec import CommonSpec

from testwrite.usint_arr_d1_lh import UsintArrD1Lh

class TestUsintArrD1Lh(CommonSpec.Base):
    def __init__(self, *args, **kwargs):
        super(TestUsintArrD1Lh, self).__init__(*args, **kwargs)
        self.struct_class = UsintArrD1Lh
        self.src_filename = 'src/USINT_ARR_D1_LH.bin'
