# Autogenerated from KST: please remove this line if doing any edits by hand!

import unittest
from specwrite.common_spec import CommonSpec

from testwrite.usint_arr_d3_lh import UsintArrD3Lh

class TestUsintArrD3Lh(CommonSpec.Base):
    def __init__(self, *args, **kwargs):
        super(TestUsintArrD3Lh, self).__init__(*args, **kwargs)
        self.struct_class = UsintArrD3Lh
        self.src_filename = 'src/USINT_ARR_D3_LH.bin'
