# Autogenerated from KST: please remove this line if doing any edits by hand!

import unittest
from specwrite.common_spec import CommonSpec

from testwrite.ulint_arr_d2_lh import UlintArrD2Lh

class TestUlintArrD2Lh(CommonSpec.Base):
    def __init__(self, *args, **kwargs):
        super(TestUlintArrD2Lh, self).__init__(*args, **kwargs)
        self.struct_class = UlintArrD2Lh
        self.src_filename = 'src/ULINT_ARR_D2_LH.bin'
