# Autogenerated from KST: please remove this line if doing any edits by hand!

import unittest
from specwrite.common_spec import CommonSpec

from testwrite.union_struct_arr_d2_e1_lh import UnionStructArrD2E1Lh

class TestUnionStructArrD2E1Lh(CommonSpec.Base):
    def __init__(self, *args, **kwargs):
        super(TestUnionStructArrD2E1Lh, self).__init__(*args, **kwargs)
        self.struct_class = UnionStructArrD2E1Lh
        self.src_filename = 'src/STRUCT_UNION_ARR_D2_E1_LH.bin'
