# Autogenerated from KST: please remove this line if doing any edits by hand!

import unittest
from specwrite.common_spec import CommonSpec

from testwrite.struct_complex_lh import StructComplexLh

class TestStructComplexLh(CommonSpec.Base):
    def __init__(self, *args, **kwargs):
        super(TestStructComplexLh, self).__init__(*args, **kwargs)
        self.struct_class = StructComplexLh
        self.src_filename = 'src/STRUCT_COMPLEX_LH.bin'
