# Autogenerated from KST: please remove this line if doing any edits by hand!

import unittest
from specwrite.common_spec import CommonSpec

from testwrite.union_struct_arr_d1_lh import UnionStructArrD1Lh

class TestUnionStructArrD1Lh(CommonSpec.Base):
    def __init__(self, *args, **kwargs):
        super(TestUnionStructArrD1Lh, self).__init__(*args, **kwargs)
        self.struct_class = UnionStructArrD1Lh
        self.src_filename = 'src/STRUCT_UNION_ARR_D1_LH.bin'
