# Autogenerated from KST: please remove this line if doing any edits by hand!

import unittest
from specwrite.common_spec import CommonSpec

from testwrite.struct_nest3_lh import StructNest3Lh

class TestStructNest3Lh(CommonSpec.Base):
    def __init__(self, *args, **kwargs):
        super(TestStructNest3Lh, self).__init__(*args, **kwargs)
        self.struct_class = StructNest3Lh
        self.src_filename = 'src/STRUCT_NEST3_LH.bin'
