# Autogenerated from KST: please remove this line if doing any edits by hand!

import unittest
from specwrite.common_spec import CommonSpec

from testwrite.struct_alignment1_arr_d1f import StructAlignment1ArrD1f

class TestStructAlignment1ArrD1f(CommonSpec.Base):
    def __init__(self, *args, **kwargs):
        super(TestStructAlignment1ArrD1f, self).__init__(*args, **kwargs)
        self.struct_class = StructAlignment1ArrD1f
        self.src_filename = 'src/STRUCT_ALIGNMENT1_ARR_D1.bin'
