# Autogenerated from KST: please remove this line if doing any edits by hand!

import unittest
from specwrite.common_spec import CommonSpec

from testwrite.struct_alignment8 import StructAlignment8

class TestStructAlignment8(CommonSpec.Base):
    def __init__(self, *args, **kwargs):
        super(TestStructAlignment8, self).__init__(*args, **kwargs)
        self.struct_class = StructAlignment8
        self.src_filename = 'src/STRUCT_ALIGNMENT8.bin'
