# Autogenerated from KST: please remove this line if doing any edits by hand!

import unittest
from specwrite.common_spec import CommonSpec

from testwrite.struct_padded_lh import StructPaddedLh

class TestStructPaddedLh(CommonSpec.Base):
    def __init__(self, *args, **kwargs):
        super(TestStructPaddedLh, self).__init__(*args, **kwargs)
        self.struct_class = StructPaddedLh
        self.src_filename = 'src/STRUCT_PADDED_LH.bin'
