# Autogenerated from KST: please remove this line if doing any edits by hand!

import unittest
from specwrite.common_spec import CommonSpec

from testwrite.struct_alignment1 import StructAlignment1

class TestStructAlignment1(CommonSpec.Base):
    def __init__(self, *args, **kwargs):
        super(TestStructAlignment1, self).__init__(*args, **kwargs)
        self.struct_class = StructAlignment1
        self.src_filename = 'src/STRUCT_ALIGNMENT1.bin'
