# Autogenerated from KST: please remove this line if doing any edits by hand!

import unittest
from specwrite.common_spec import CommonSpec

from testwrite.struct_small_arr_d2_lh import StructSmallArrD2Lh

class TestStructSmallArrD2Lh(CommonSpec.Base):
    def __init__(self, *args, **kwargs):
        super(TestStructSmallArrD2Lh, self).__init__(*args, **kwargs)
        self.struct_class = StructSmallArrD2Lh
        self.src_filename = 'src/STRUCT_SMALL_ARR_D2_LH.bin'
