# Autogenerated from KST: please remove this line if doing any edits by hand!

import unittest
from specwrite.common_spec import CommonSpec

from testwrite.struct_small_arr_d3_lh import StructSmallArrD3Lh

class TestStructSmallArrD3Lh(CommonSpec.Base):
    def __init__(self, *args, **kwargs):
        super(TestStructSmallArrD3Lh, self).__init__(*args, **kwargs)
        self.struct_class = StructSmallArrD3Lh
        self.src_filename = 'src/STRUCT_SMALL_ARR_D3_LH.bin'
