# Autogenerated from KST: please remove this line if doing any edits by hand!

import unittest
from specwrite.common_spec import CommonSpec

from testwrite.struct_padded_arr_d1_lh import StructPaddedArrD1Lh

class TestStructPaddedArrD1Lh(CommonSpec.Base):
    def __init__(self, *args, **kwargs):
        super(TestStructPaddedArrD1Lh, self).__init__(*args, **kwargs)
        self.struct_class = StructPaddedArrD1Lh
        self.src_filename = 'src/STRUCT_PADDED_ARR_D1_LH.bin'
