# Autogenerated from KST: please remove this line if doing any edits by hand!

import unittest
from specwrite.common_spec import CommonSpec

from testwrite.struct_small_arr_d2f_lh import StructSmallArrD2fLh

class TestStructSmallArrD2fLh(CommonSpec.Base):
    def __init__(self, *args, **kwargs):
        super(TestStructSmallArrD2fLh, self).__init__(*args, **kwargs)
        self.struct_class = StructSmallArrD2fLh
        self.src_filename = 'src/STRUCT_SMALL_ARR_D2_LH.bin'
