# Autogenerated from KST: please remove this line if doing any edits by hand!

import unittest
from specwrite.common_spec import CommonSpec

from testwrite.struct_small_arr_d3f_lh import StructSmallArrD3fLh

class TestStructSmallArrD3fLh(CommonSpec.Base):
    def __init__(self, *args, **kwargs):
        super(TestStructSmallArrD3fLh, self).__init__(*args, **kwargs)
        self.struct_class = StructSmallArrD3fLh
        self.src_filename = 'src/STRUCT_SMALL_ARR_D3_LH.bin'
