# Autogenerated from KST: please remove this line if doing any edits by hand!

import unittest
from specwrite.common_spec import CommonSpec

from testwrite.struct_padded_arr_d2_e1_lh import StructPaddedArrD2E1Lh

class TestStructPaddedArrD2E1Lh(CommonSpec.Base):
    def __init__(self, *args, **kwargs):
        super(TestStructPaddedArrD2E1Lh, self).__init__(*args, **kwargs)
        self.struct_class = StructPaddedArrD2E1Lh
        self.src_filename = 'src/STRUCT_PADDED_ARR_D2_E1_LH.bin'
