# Autogenerated from KST: please remove this line if doing any edits by hand!

import unittest
from specwrite.common_spec import CommonSpec

from testwrite.struct_small_lh import StructSmallLh

class TestStructSmallLh(CommonSpec.Base):
    def __init__(self, *args, **kwargs):
        super(TestStructSmallLh, self).__init__(*args, **kwargs)
        self.struct_class = StructSmallLh
        self.src_filename = 'src/STRUCT_SMALL_LH.bin'
