# Autogenerated from KST: please remove this line if doing any edits by hand!

import unittest
from specwrite.common_spec import CommonSpec

from testwrite.struct_padded_arr_d1_e1_lh import StructPaddedArrD1E1Lh

class TestStructPaddedArrD1E1Lh(CommonSpec.Base):
    def __init__(self, *args, **kwargs):
        super(TestStructPaddedArrD1E1Lh, self).__init__(*args, **kwargs)
        self.struct_class = StructPaddedArrD1E1Lh
        self.src_filename = 'src/STRUCT_PADDED_ARR_D1_E1_LH.bin'
