# Autogenerated from KST: please remove this line if doing any edits by hand!

import unittest
from specwrite.common_spec import CommonSpec

from testwrite.struct_padded_arr_d3_e1_lh import StructPaddedArrD3E1Lh

class TestStructPaddedArrD3E1Lh(CommonSpec.Base):
    def __init__(self, *args, **kwargs):
        super(TestStructPaddedArrD3E1Lh, self).__init__(*args, **kwargs)
        self.struct_class = StructPaddedArrD3E1Lh
        self.src_filename = 'src/STRUCT_PADDED_ARR_D3_E1_LH.bin'
