# Autogenerated from KST: please remove this line if doing any edits by hand!

import unittest
from specwrite.common_spec import CommonSpec

from testwrite.struct_small_arr_d1_lh import StructSmallArrD1Lh

class TestStructSmallArrD1Lh(CommonSpec.Base):
    def __init__(self, *args, **kwargs):
        super(TestStructSmallArrD1Lh, self).__init__(*args, **kwargs)
        self.struct_class = StructSmallArrD1Lh
        self.src_filename = 'src/STRUCT_SMALL_ARR_D1_LH.bin'
