# Autogenerated from KST: please remove this line if doing any edits by hand!

import unittest
from specwrite.common_spec import CommonSpec

from testwrite.struct_small_arr_d2_e1_lh import StructSmallArrD2E1Lh

class TestStructSmallArrD2E1Lh(CommonSpec.Base):
    def __init__(self, *args, **kwargs):
        super(TestStructSmallArrD2E1Lh, self).__init__(*args, **kwargs)
        self.struct_class = StructSmallArrD2E1Lh
        self.src_filename = 'src/STRUCT_SMALL_ARR_D2_E1_LH.bin'
