# Autogenerated from KST: please remove this line if doing any edits by hand!

import unittest
from specwrite.common_spec import CommonSpec

from testwrite.struct_alignment4 import StructAlignment4

class TestStructAlignment4(CommonSpec.Base):
    def __init__(self, *args, **kwargs):
        super(TestStructAlignment4, self).__init__(*args, **kwargs)
        self.struct_class = StructAlignment4
        self.src_filename = 'src/STRUCT_ALIGNMENT4.bin'
